= Publications en anglais

IMPORTANT: Barandiaran, X., Calleja-López, A. & Monterde, A. (2018). Decidim: réseaux politiques et technopolitiques
pour la démocratie participative. __Papier blanc du projet Decidim__. (Vous pouvez http://ajbcn-meta-decidim.s3.amazonaws.com/uploads/decidim/attachment/file/2005/White_Paper.pdf[télécharger une version alpha du document ici])

== Universitaire

* Borge, R., Balcells, J. , Padró-Solanet, A. (2019) "A model for the analysis of online citizen deliberation: Barcelona case study", International Journal of Communication. 13, p. 5671–5695. https://ijoc.org/index.php/ijoc/article/view/10805/2157

== Médias

* Preville, P. (2019, 13 novembre) _Comment Barcelone mène une nouvelle ère de démocratie numérique_ https://medium.com/sidewalk-talk/comment-barcelona-is-leading-a-new-era-of-digital-Democry-4a033a98cf32
* Graham, T. (2018, 18 mai) - _Barcelone mène la lutte contre la surveillance intelligente de la ville_ https://www.wired.co.uk/article/barcelona-decidim-ada-colau-francesca-bria-decode
* Barandiaran, X. E., & iaran. (2018, 24 avril). _Qu'est-ce que Decidim?_ https://xabier.barandiaran.net/2018/04/24/what-is-decidim/ +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract. Beaucoup de gens se demandent ce qui est ce projet appelé « Decidim » auquel j'ai consacré mes deux dernières années de travail avec un dévouement total. Je voulais partager ici un bref résumé. Ce texte est le mot de passe…:[</div>
* Stark, K. (2017, Mai 9). Decidim propose _Barcelone une plateforme open source pour les projets participatifs pour la démocratie. https://www.shareable.net/blog/barcelonas-decidim-offers-open-source-platform-for-participatory-democratiy-projects +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract. Le mot Decidim traduit du catalan signifie que nous décidons, et c’est le nom de l’infrastructure numérique de Barcelone pour la démocratie participative. Une partie de la base de données fonctionnelle et une partie des déclarations politiques, Selon les organisateurs, Decidim est la clé d'une vaste transformation numérique qui se déroule à Barcelone - ses institutions, ses marchés et son économie. Ass:[</div>]
* _Decidim: Libérer la démocratie participative Open-Source pour les villes et les organisations | Hacker News_. (n.d.). Récupéré le 21 janvier 2019, sur https://news.ycombinator.com/item?id=18952328
* Oikos Denktank. (n.d.). _(W)E-Démocratie - orateur 5 (1) - villes E-démocratiques - Arnau Monterde et Xabier E. Barandiaran_. Récupéré le 30 août 2017, sur https://www.youtube.com/watch?v=qrQ8ij4Ekag