= Publications en espagnol

== Universitaire

* Barandiaran, X. E., Calleja, A., Monterde, A., Aragón, P., Linares, J., Romero, C., & Pereira, A. (2017). Decidim: Redes políticas y tecnopolíticas para la democracia participativa. __Recerca__. Revista de pensament i anaÄlisi., 21, 137-150. https://doi.org/10.6035/Recerca.2017.21.8
* Barandiaran, X. E. (2019). Tecnopolítica, municipalismo y radicalización democrática. In L. Roth, A. Monterde, & A. Calleja-Lopez (Eds.), _Ciudades Democráticas. La revuelta municipalista en el ciclo post-15M_ (pp. 173–207). Icaria. http://ciudadesdemocraticas.tecnopolitica.net/
* Borge, R., Balcells, J., Padró-Solanet, A., Batlle, A., Orte, A., & Serra, R.  (2018) La participación política a través de la plataforma Decidim: análisis de 11 municipios catalanes. Paper presentado en el IX Congreso Internacional en Gobierno, Administración y Políticas Públicas GIGAPP. Madrid, 24-27 Septiembre. https://dryfta-assets.s3-accelerate.<unk> assets/congreso2018/abstractfiles/1536574598Laparticipacion_politica_a_traves_de_la_plataforma_Decidim.pdf
* SolaÄ, J. (2018). _Comment sont prises les décisions de Decidim.barcelona_ [Maître Thèse, Pompeu Fabra]. https://repositori.upf.edu/handle/10230/36105
* Barandiaran, X. E., Monterde, A., & Pin, G. (2016a). Decidim.barcelona: autonomia, participació i programari lliure. In Xarxaip (Ed.), _Programari lliure i de codi obert-Societat lliure i govern obert._ (pp. 31–32).
* Barandiaran, X. E., Monterde, A., & Pin, G. (2016b). Decidim.barcelona: autonomiéa, participación y software libre - Software libre. In Xarxaip (Ed.), _Programari lliure i de codi obert-Societat lliure i govern obert._ (pp. 31–32). http://softwarelibre.xarxaip.cat/18.html
* Aragón, P., Kaltenbrunner, A., Calleja-López, A., Pereira, A., Monterde, A., Barandiaran, X. E., & Gómez, V. (2017). Deliberative Platform Design: The Case Study of the Online Discussions in Decidim Barcelona. _Informatics_, 277–287. https://doi.org/10.1007/978-3-319-67256-4_22 +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract. Avec l'irruption des TIC et la crise de la représentation politique, de nombreuses plateformes en ligne ont été développées dans le but d’améliorer les processus démocratiques participatifs. Toutefois, en ce qui concerne les plates-formes pour les pétitions en ligne, les recherches précédentes n'ont pas trouvé d'exemples sur la manière d'introduire efficacement les discussions, un élément crucial pour promouvoir la délibération. Dans cette étude, nous nous concentrons sur le cas de Decidim Barcelone, la plate-forme participative-démocratie en ligne lancée par le conseil municipal de Barcelone dans laquelle les propositions peuvent être discutées avec une interface qui combine discussions et alignement des commentaires sur la proposition. Cette approche novatrice permet de déterminer si des commentaires neutres, positifs ou négatifs sont plus susceptibles de générer des cascades de discussion. Les résultats révèlent que, avec cette interface, les commentaires marqués comme étant négativement alignés sur la proposition étaient plus susceptibles d'impliquer les utilisateurs dans les discussions en ligne et, a donc contribué à promouvoir la prise de décisions délibératives. Ass:[</div>]

== Médias

* Calleja-López, A., Monterde, A., & Barandiaran, X. E. (2017, 18 octobre). _De las redes sociales a las redes (tecno)políticas: redes de tercera generación para la democracia del siglo XXI_ [Text]. http://tecnopolitica.net/content/de-las-redes-sociales-las-redes-tecnopol%C3%ADticas-redes-de-tercera-generaci%C3%B3n-para-la +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract.# La sociedad deviene (fr) red.pass:[</div>]
* _TIPS - Cultura digital - La démocratie 2.0_. (2017, février 2). http://www.rtve.es/alacarta/videos/tips/tips-cultura-digital-democracia-20/3896837/ +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract. TIPS - Cultura digital - La Democracia 2.0, Trucs online, completo y gratis en RTVE.es A la Carta. Todos los programas de Tips online en RTVE.es A la Cartapass:[</div>]

[[ref-4881969-FWFFK8LS]]
* Bravo, E. (2016, Juillet 20). _Cómo mejorar Barcelona con la participación de sus ciudadanos_ [Magazzine]. http://www.yorokobu.es/barcelona-participacion/ +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract.# El cricket es un deporte muy curioso. Los partidos pueden durar días y, entre sus reglas, está la de parar el juego para tomar el té. Una de las potencias en este deporte es Paquistán, país del que procede parte de la población inmigrante de Barcelona. Muchos de los miembros de esa comunidad llevan años […]pass:[</div>]
* Barandiaran, X. E., Pereira, A., Monterde, A., & Calleja-López, A. (2016). _Plan de desarrollo Decidim Barcelona_. Ajuntament de la Mairie de Barcelone https://decidim-barcelona.s3.amazonaws.com/uploads/decidim/attachment/file/54/Plan_desarrollo_decidim.pdf +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract. This documento detalla el futuro desarrollo de la plataforma digital de participación de la ́juntament de Barcelona, decidim.barcelona (disponible en URL https://decidim.barcelona). Los principales objetivos de la plataforma son articular, estandarizar, visualizar y comunicar todos los procesos de participación del Ajuntament de Barcelona y de la ciudad ofreciendo un servicio de infraestructura digital para la democracia directa y participativa a todas las escalas territoriales y asociativas de Barcelona. El documento detalla los objetivos de la plataforma, el flujo de desarrollo, las funcionalidades previstas, y un código ético-político.pass:[</div>]
* Participa Pamplona. (2017a, 18 juillet). _Decidim Barcelona (Xabier Barandiaran)_. https://www.youtube.com/watch?v=zQYvdwGsg8M +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract.# 1a Jornada de tecnología y Democracia (24/05/2017). Infraestructuras digitales pour la démocratie. Decidim Barcelona Xabier Barandiaran. Coordinador del proyecto Decidim, asesor de la Regiduría de Participación del Ayuntamiento de Barcelona. Teknologia eta demokraziari buruzko 1. jardunaldia (24/05/2017). Demokrazia partizipatiborako azpiegitura digitalak Decidim Barcelona Xabier Barandiaran. Decidim proiektuaren koordinatzailea eta Bartzelonako Udaleko Partaidetza zinegotziaren aholkulariapass:[</div>]
* Participa Pamplona. (2017b, Juillet 18). _Hacia una Democracia participativa inteligente y democrática (Asier Gallastegui y Asier Amezaga)_. https://www.youtube.com/watch?v=z4FTUt8wnRs +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract.# 1a Jornada de tecnología y Democracia (24/05/2017). Infraestructuras digitales pour la démocratie. Decidim Barcelona Xabier Barandiaran. Coordinador del proyecto Decidim, asesor de la Regiduría de Participación del Ayuntamiento de Barcelona. Teknologia eta demokraziari buruzko 1. jardunaldia (24/05/2017). Demokrazia partizipatiborako azpiegitura digitalak Decidim Barcelona Xabier Barandiaran. Decidim proiektuaren koordinatzailea eta Bartzelonako Udaleko Partaidetza zinegotziaren aholkulariapass:[</div>]
* Participa Pamplona. (2017c, 18 juillet). _Metadecidim. Diseño participativo de la plataforma Decidim Barcelona (Andrés Pereira de Lucena)_. https://www.youtube.com/watch?v=I31yY4ip3rk +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract.# 1a Jornada de tecnología y Democracia (24/05/2017). Infraestructuras digitales pour la démocratie. Andrés Pereira de Lucena. Presidente de la asociación aLabs, coordinador técnico y arquitecto técnico de Decidim. Teknologia eta demokraziari buruzko 1. jardunaldia (24/05/2017). Demokrazia partizipatiborako azpiegitura digitalak Andrés Pereira de Lucena. aLabs elkarteko lehendakaria eta Dicidimen koordinatzaile teknikoa eta arkitekto teknikoa.pass:[</div>]
* Barandiaran, X. E., & Romero, C. (2018, May 17). _Presentació Decidim Ada Lovelace_. https://www.youtube.com/watch?v=-3eh_v339Cg
* Barcelona Activa. (n.d.). _FoÄrum d’Economies Col·laboratives Procomuns 2017. Activitat paral·lela 3_. Récupéré le 13 janvier 2018, sur https://www.youtube.com/watch?v=IvDsgJcNxnQ
* Gouvernez le numérique. (n.d.). _CGDL2018 - Participació ciutadana: com fer de la política quelcom més proper_. Récupéré le 9 avril 2018, sur https://www.youtube.com/watch?v=7LH6OItIrRU