= Fundo

:experimental:
:icons: font
:page-partial:
:source-highlighter: Destacar

== Participação do cidadão na Sociedade da Rede

Tornando-se uma sociedade da rede(). As tecnologias da informação e da comunicação (doravante, as TIC) e as suas práticas associadas estão a provocar alterações irreversíveis na paisagem social e política. Da mais pequena associação de residentes à mais intensa campanha eleitoral, de uma organização de vizinhança ou de um movimento social até à União Europeia, As relações políticas são cada vez mais determinadas pela utilização de dispositivos e tecnologias digitais. Parece que o futuro da participação democrática e da acção colectiva será através do desenvolvimento de plataformas digitais e processos híbridos, que renovam as práticas tradicionais e as combinam com as práticas digitais (Fuchs, 2007).

Esta transição coincide com o declínio dos sistemas representativos nas últimas décadas (Norris, 1999; Pharr & Putnam, 2000; Tormey, 2015), que contribuiu para questionar a legitimidade e o próprio sentido da democracia, reduzido e frequentemente identificado com este sistema (Crouch, 2004; Keane, 2009; Streeck, 2016). Vários autores utilizaram os termos “pós-representação” para se referirem à esvaziação do poder e do significado das instituições representativas que vão da globalização ao desafecto e ao desinvestimento dos cidadãos (Brito Vieira e Rúnciman, 2008; Keane, 2009; Rosanvallon, 2011; Tormey, 2015). As várias tentativas de impulsionar a participação revelaram-se desiguais à tarefa de inverter estas tendências (Keane, 2011; Tormey, 2015).

Esta crise política de longa data vem no seguimento da crise financeira e económica de 2008 e está directamente ligada a esta crise anterior. Mesmo assim, milhões de pessoas mobilizaram-se perante a crise. A intenção não só de exigir, mas também de experimentar e construir uma verdadeira democracia. O principal desenvolvimento aqui foi o movimento de rede 15M. É no contexto da hipermediação tecnológica que as tecnologias da informação e da comunicação utilizados nos anos 80 e 90 para acelerar os fluxos financeiros e a globalização (Castells, 1996), tornou-se espaços e dispositivos cruciais para uma reapropriação multituária de políticas, bem como uma experimentação democrática (Martinet Ros e al. 2015).

Após quatro anos de numerosos êxitos e fracassos, as novas iniciativas políticas de cidadania, em Maio de 2015, conseguiram tomar o poder nas principais cidades espanholas, incluindo Barcelona. A este respeito, estavam a andar na maré de países como a Islândia, onde a crise económica conduziu a um período de reapropriação das instituições por parte dos cidadãos e a uma inovação democrática fértil. baseado numa utilização intensa e criativa das TIC.

Desde 15M, a maioria das experiências destinadas a introduzir novas formas de democracia participativa e deliberativa (Barber, 1984; Habermas, 1994, 1996; Della Porta 2013) foi tecnologicamente mediada. Como se pode ver pelo caso da Islândia (bem como outros, como a Finlândia), os processos de democratização da mobilização e da capacitação dos cidadãos exigem uma coordenação tecno-política (Rodotaprocedures, 1997; Ros de Martinet et al. 2015) para alcançar a sua máxima riqueza e capacidade. A tecnopolítica resulta da politização das tecnologias e da reconstituição tecnológica da política, bem como do co-desenvolvimento e da co-produção da política e das tecnologias. Quanto às formas de participação e deliberação tecno-política, práticas digitais e presenciais, espaços e processos se conectam e se alimentam uns dos outros, adquirindo uma dimensão em várias camadas. Estes dispositivos participativos estão orientados para aumentar o número variedade e paridade de jogadores que "tomam partição" no governo comum da cidade, expandindo e enriquecendo as áreas, formas e períodos em que isso acontece e ajudando a impulsionar uma inteligência coletiva (Levy, 1997) capaz de assumir a complexidade da vida urbana actual. Tecnopolítica precisa resolver os numerosos limites do que tem sido chamado de "democracia digital" (Hindman, homem, 2008) começando por se libertar das narrativas tecnocêntricas e tecnootimistas em torno da participação digital mediada.

Estão a ser construídos novos processos participativos num contexto cheio de oportunidades e cheio de riscos. O programa governamental de 2015 e Programa de Acção Municipal (PAM) para 2016-2019, elaborado para a cidade de Barcelona, dá um lugar central à participação e, mais especificamente, a inovação e o desenvolvimento de novos modelos de participação democrática. PAM, dessas, cujo desenvolvimento envolveu milhares de pessoas. atende a uma exigência social clara que apela a uma reformulação completa do sistema democrático e dos seus mecanismos participativos. No entanto, isto ocorre num contexto definido por: a) grandes sectores da população politicamente excluídos, económica e socialmente; b) aumento da dificuldade de acesso à participação em consequência da situação de crise económica; c) uma crise sobre a legitimidade e a operacionalidade do sistema democrático representativo e das autoridades públicas; d) uma enorme dependência tecnológica das infra-estruturas e serviços empresariais privados; e) um contexto jurídico e político adverso à democracia, à independência social e à soberania territorial; f) uma desvantagem institucional abismal na compreensão de complexidades sociais através de técnicas que analisem os dados de comportamento social e modelos que as grandes empresas tecnológicas e os serviços digitalmente coordenados.

[[h.2et92p0]]
== Controle de dados e infra-estruturas digitais para a democracia

No contexto de novas configurações de capitalismo informativo (Castells, 1996), o chamado “capitalismo de dados” (Lohr, 2015; Morozov, 2015) ou "capitalismo de vigilância" (Zuboff, 2015), as novas infra-estruturas digitais da democracia correm o risco de contribuir para dinâmicas contrárias a princípios como a privacidade e a soberania tecnológica. Exclusivo, plataformas fechadas e opacas orientadas para a exploração das actividades sociais para o lucro das empresas estão a funcionar como espaços não democráticos que ocupam cada vez mais áreas da vida social. Este modelo é particularmente perigoso em relação às novas infra-estruturas e processos democráticos de que estamos a falar.

Comparado com o modelo de infra-estruturas exclusivo e empresarial, o modelo comum público, que consideramos decidido. o desenvolvimento da arcelona tem de ser inspirado porquê? is orientados para o desenvolvimento de plataformas onde a concepção, propriedade e gestão são livres, abertos e participativos, compartilhados entre funcionários públicos e cidadãos (organizados ou não). Com este modelo, não só o código da plataforma, mas também os dados que são gerados nele, são processados e apropriados de acordo com a lógica da gestão pública e comum. A abertura de tudo e qualquer coisa à participação, a marca dos comuns como um princípio político (ao contrário da esfera privada e mesmo pública-estatal) --- Laval e Dardot, 2015) parece ser uma condição básica para que as infra-estruturas participativas sejam plenamente funcionais. A participação tem de ser recursiva aqui: precisa de ajudar a definir e estabelecer as condições infra-estruturais da sua própria existência e a afectar a concepção, desenvolvimento e gestão de plataformas participativas digitais, bem como dos processos e resultados (e. . dados) que são gerados neles.

Ponha nas mãos de grandes corporações de serviços digitais, da organização algorítmica da vida social e da área com que nos preocupamos. participação política, representa um risco para a democracia e a soberania tecnológica, que só um esforço comum dos cidadãos em matéria de infra-estruturas digitais pode inverter. Apenas plataformas baseadas em software de gestão livre, aberto, transparente, seguro e público comum oferecem garantias quando se trata de construir democracias de maior qualidade. A democracia do futuro tem, portanto, de ser construída com base em infra-estruturas democráticas.