= Contrato Social do Decididor

[NOTE]
====
Você também pode ler o Contrato Social da Decidim em outros idiomas: xref:understand:social-contract-ca.adoc[Català] - xref:understand:social-contract-es.adoc[Castellano]

Se você quiser traduzi-lo para seu próprio idioma, por favor https://decidim.org/contact[entre em contato conosco].
====

Código para garantias democráticas e colaboração aberta

Este é o contrato social que todos os membros da comunidade Decidim estão comprometidos a seguir.

Ao assinar este Contrato Social, qualquer indivíduo, instituição ou grupo social de qualquer tipo, Comprometemo-nos a cumprir os princípios estabelecidos aqui ao usar, desenvolver e participar da comunidade de Decidim.

== Software livre e conteúdo aberto

O código da plataforma, juntamente com os módulos, bibliotecas ou qualquer outro código desenvolvido para o seu funcionamento e implantação, sempre será Software de código aberto gratuito com um https://www. nu.org/licenses/agpl-3.0.en.html[Licença Affero GPLv3 ou versões posteriores] sempre que o código for recentemente desenvolvido e com licenças que são compatíveis com o acima, quando o código for reutilizado.

Da mesma forma, conteúdo, dados, APIs e/ou quaisquer outras interfaces que são implantadas para interagir com qualquer tipo de usuário devem seguir padrões abertos e interoperáveis (ex. OpenID, RSS, OStatus, etc.), sempre tende a maximizar sua integração com os padrões abertos mais usados.

A fim de maximizar a transparência e a colaboração dos cidadãos em processos participativos, órgãos e mecanismos, o conteúdo, texto, gráficos, fontes, áudio, vídeo ou outros elementos de design serão publicados sob uma https://creativecommons. rg/licenses/by-sa/4.0/legalcode[Creative Commons By-SA].

Os dados disponíveis através da plataforma, especialmente todos os dados que podem ser coletados de forma sistemática através de sucatas ou outras técnicas de consulta massiva, será publicado e licenciado sob a licença http://opendatacommons. rg/licenses/odbl[Open Data Commons Open Database License], publicado em formatos padronizados e acessíveis (como CSV, JSON, etc.) e, sempre que possível, com ferramentas que facilitam a análise e a visualização de dados.

== Transparência, rastreabilidade e integridade

A plataforma, e as suas actuais ou futuras configurações, desenvolvimento, implantação e utilização devem assegurar e maximizar, sempre, a transparência, rastreabilidade e integridade de documentos, propostas, debates, decisões ou qualquer outro objeto, mecanismo ou processo participativo.

Por _transparência_ entendemos que todos os dados relacionados a todos os mecanismos e processos participativos estão disponíveis para download, análise e tratamento, seguindo os padrões e formatos mais exigentes para compartilhar informações (acessibilidade, multi-formatos, etc.).

A transparência é uma condição necessária para o controlo dos processos e mecanismos participativos, mas nunca deverá, em todo o caso, ser controlada. seja aplicado no tratamento de dados pessoais ou contra a defesa da privacidade das pessoas que participam na plataforma.

Entendemos pela _rastreabilidade_ a capacidade de rastrear completamente o caminho para trás (passado) e para a frente (futuro) o que aconteceu às propostas, planos, regulamentos, ou qualquer outro objectivo de participação ou decisão incluído num processo ou mecanismo. A plataforma deve mostrar em todos os momentos como, porquê, por quem e com que garantias um certo tipo de objeto de um processo participativo foi rejeitado, aprovado ou bloqueado.

Nós entendemos por _integrity_ a autenticidade de um conteúdo específico e assegurar que não tenha sido adulterado ou alterado sem que esta modificação tenha sido claramente registada e visivelmente verificável e auditável. O objetivo da integridade é evitar a manipulação de propostas ou resultados de processos ou mecanismos participativos.

== Oportunidades iguais e indicadores de qualidade

Paralelamente às garantias previamente definidas, a plataforma promete assegurar igualdade de oportunidades para todas as pessoas. bem como para suas propostas ou outras contribuições que a plataforma pode hospedar. A plataforma oferecerá igualdade de oportunidades de início a todos os objetos participativos (propostas, debates, etc.) para serem vistos, discutidos, comentados, avaliados ou tratados sem qualquer tipo de discriminação. Nesse sentido, a identidade digital dos usuários da plataforma será sempre pessoal e não transferível, a verificação que confere direitos de decisão na plataforma também deve ser única, e é a entidade administrativa responsável pela plataforma que deve ser responsável por garantir a não personificação de uma pessoa ou entidade.

A plataforma deve promover, com o objectivo de garantir a sua qualidade democrática, o uso de indicadores de qualidade desenvolvidos com base nos dados obtidos a partir de processos participativos, mecanismos e atividade do usuário. O compartilhamento da configuração dos diferentes componentes e dados abertos serão promovidos para a definição desses indicadores

A igualdade na participação política dos cidadãos é um dos princípios fundamentais de qualquer sistema democrático e da plataforma. Não só tem de garantir a igualdade de oportunidades no que diz respeito às utilizações e funções, como também ao direito de acesso. Nesse sentido, a entidade responsável pela plataforma assume o compromisso de promover ações que avancem na direção de fornecer acesso e apoio à plataforma para todos os cidadãos, da mesma forma que doar universalmente ferramentas e recursos apropriados para a plataforma está disponível para qualquer um que queira usar.

== Segredo de dados

A confidencialidade e a privacidade dos dados pessoais que as pessoas possam fornecer para participar em qualquer uma das funcionalidades e/ou possibilidades de participação que a plataforma fornece serão garantidas a todo momento. Em caso algum os dados pessoais serão transferidos para terceiros. Dados pessoais não serão usados além do que é estritamente necessário para fins de registro de usuários e melhorias na usabilidade da plataforma. Sempre que a tecnologia da plataforma o torne possível, a expressão de preferências políticas ou vontade nos processos de tomada de decisão permanecerá inacessível, mesmo para o administrador da plataforma ou para os servidores/os que a hospedam

== Responsabilidade e responsabilidade

Será assumido um compromisso para com os cidadãos no sentido de responder a todas as dúvidas e contribuições no mais curto espaço de tempo possível. Deverá igualmente ser assumido um compromisso no sentido de dar seguimento aos resultados dos processos participativos e de responder às exigências específicas que o solicitem. Por último, será assumido o compromisso de estudar a incorporação de indicadores para monitorizar os processos de participação após a sua conclusão. A fim de avaliar sistematicamente a sua aplicação.

== Melhoria contínua e colaboração interinstitucional

Serão fornecidos mecanismos de revisão e avaliação periódicas a fim de facilitar a melhoria contínua da plataforma.

Será dada prioridade à colaboração e ao intercâmbio de experiências entre as instituições envolvidas no projecto, com o objetivo de melhorar, consertar e construir novos desenvolvimentos para a melhoria contínua da plataforma.

Neste sentido, as condições e ambientes de colaboração serão facilitados quando se avançar melhorias que apontam para um benefício comum de toda a plataforma, permitir mecanismos de coordenação interagências, quando necessário.