= Inicializador de Iniciativas

Para usar o módulo de iniciativas, você vai querer revisar as configurações que estão no inicializador. Veja a xref:configure:initializer.adoc[configuração geral do Inicializador] para mais informações sobre este arquivo.

Você precisará alterar o arquivo `config/initializer/decidim.rb`. Você também pode criar um arquivo ad-hoc para essas configurações, como `config/initializer/initiatives.rb`.

Após fazer alterações neste arquivo você precisa reiniciar o servidor da sua aplicação.

== Criação ativada

Configuração que define se a criação é ou não permitida para qualquer usuário validado. O padrão é verdadeiro.

[source,ruby]
....
  config_accessor :creation_enabled do
    true
  end
....

== Limite de similaridade

Definindo que define o valor mínimo de similaridade para considerar duas iniciativas
similares. O padrão é 0.25.

[source,ruby]
....
  config_accessor :similarity_threshold do
    0.25
  end
....

== Limite de similaridade

Definição que define quantas iniciativas semelhantes serão mostradas.
O padrão é 5.

[source,ruby]
....
  config_accessor :similarity_limit do
    5
  end
....

== Mínimo de membros do comitê

Número mínimo de membros do comitê necessários para passar a iniciativa para
etapa de validação técnica. Only applies to initiatives created by
individuals.

[source,ruby]
....
  config_accessor :minimum_committee_members do
    2
  end
....

== Duração do período de tempo de assinatura padrão

Número de dias disponíveis para coletar suportes depois que uma iniciativa tiver sido
publicada.

[source,ruby]
....
  config_accessor :default_signature_time_period_length do
    120
  end
....

== Componentes predefinidos

Componentes ativados para uma nova iniciativa

[source,ruby]
....
  config_accessor :default_components do
    [:pages, :meetings]
  end
....

== Primeira porcentagem da notificação

Notifica quando a determinada porcentagem de suportes é alcançada para uma iniciativa
.

[source,ruby]
....
  config_accessor :first_notification_percentage do
    33
  end
....

== Segunda porcentagem de notificação

Notifica quando a determinada porcentagem de suportes é alcançada para uma iniciativa
.

[source,ruby]
....
  config_accessor :second_notification_percentage do
    66
  end
....

== Expiração do cache de estatísticas

Define o tempo de expiração para os dados de estatística.

[source,ruby]
....
  config_accessor :stats_cache_expiration_time do
    5.minutes
  end
....

== Tempo máximo de validação de estado

Quantidade máxima de tempo na validação do estado.
Após esta vez, a iniciativa será transferida para
estado descartado.

[source,ruby]
....
  config_accessor :max_time_in_validating_state do
    60.days
  end
....

== Impressão ativada

Funcionalidade de impressão habilitada. Permite ao usuário obter a versão
impressa da iniciativa do painel de administração
.

[source,ruby]
....
  config_accessor :print_enabled do
    true
  end
....

== Serviço Timestamp

Defina um serviço para gerar um timestamp em cada votação. O atributo
é o nome de uma classe cujas instâncias são
inicializadas com uma seqüência de caracteres que contém os dados para ser
timestamped e responder a um método de marcação de tempo.

[source,ruby]
....
  config_accessor :timestamp_service
....

== Serviço de assinatura PDF

Defina um serviço para adicionar uma assinatura ao PDF de assinaturas.
O atributo é o nome de uma classe cujas instâncias são
inicializadas com o documento a ser assinado e responder a um método
signed_pdf com a assinatura adicionada.

[source,ruby]
....
  config_accessor :pdf_signature_service
....

== Não requerer autorização

Este sinalizador permite criar autorizações para usuários não autorizados.

[source,ruby]
....
  config_accessor :do_not_require_authorization do
    false
  end
....