= Englische Publikationen

IMPORTANT: Barandiaran, X., Calleja-López, A. & Monterde, A. (2018). Dezidim: Politische und technopolitische
Netzwerke für partizipative Demokratie. __Decidim's Projekt White paper__. (Sie können http://ajbcn-meta-decidim.s3.amazonaws.com/uploads/decidim/attachment/file/2005/White_Paper.pdf[hier eine Alpha-Version des Dokuments herunterladen])

== Akademisch

* Borge, R., Balcells, J. , Padro<unk> -Solanet, A. (2019) "A model for the analysis of online citizens deliberation: Barcelona case study", International Journal of Communication. 13, S. 5671–5695. https://ijoc.org/index.php/ijoc/article/view/10805/2873

== Medien

* Preville, P. (2019, 13. November) _Wie Barcelona eine neue Ära der digitalen Demokratie führt_ https://medium.com/sidewalk-talk/how-barcelona-is-leading-a-new-era-of-digital-democracy-4a033a98cf32
* Graham, T. (2018, 18. Mai) - _Barcelona führt den Kampf gegen intelligente Stadtüberwachung durch https://www.wired.co.uk/article/barcelona-decidim-ada-colau-francesca-bria-decode
* Barandiaran, X. E., & iaran. (2018, 24. April). _Was ist Decidim?_ https://xabier.barandiaran.net/2018/04/24/what-is-decidim/ +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract. Viele fragen sich, was dieses Projekt als „Decidim“ bezeichnet, dem ich meine letzten zwei Jahre Arbeit mit voller Hingabe gewidmet habe. Ich wollte hier eine kurze Zusammenfassung abgeben. Dieser Text ist das…Pass:[</div>]
* Stark, K. (2017, 9. Mai). _Barcelonas Decidim bietet Open-Source-Plattform für partizipative Demokratie-Projekte_. https://www.shareable.net/blog/barcelonas-decidim-offers-open-source-platform-for-participatory-democracy-projects +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract. Das Wort Decidim von Katalanisch bedeutet, dass wir entscheiden, und es ist der Name von Barcelonas digitaler Infrastruktur für partizipatorische Demokratie. Ein Teil funktionale Datenbank und ein Teil politische Erklärung, Der Decidim ist der Schlüssel zu einem umfassenden digitalen Wandel, der sich in Barcelona vollzieht – seinen Institutionen, Märkten und Wirtschaft. ass:[</div>]
* _Decidim: Freie Open-Source-Demokratie für Städte und Organisationen | Hacker News_. (n.d.). Erhalte 21. Januar 2019 von https://news.ycombinator.com/item?id=18952328
* Oikos Denktank. (n.d.). _(W)E-Demokratie - Sprecher 5 (1) - E-demokratische Städte - Arnau Monterde und Xabier E. Barandiaran_. Abgerufen 30. August 2017, von https://www.youtube.com/watch?v=qrQ8ij4Ekag