= Deutsche Publikationen

== Medien

* Macher, J. (2020, March 4), _Barcelonas Erfolg mit der Plattform Decidim. Deutschlandfunk_ https://www.deutschlandfunk.de/wenn-buerger-politik-gestalten-barcelonas-erfolg-mit-der.795.de.html?dram:article_id=471680
* Huber, P. (2019, May 29), _In Barcelona schreiben die Bürger das Regierungsprogramm selbst – und machen ihre Stadt sozialer_ https://kontrast.at/barcelona-smart-city-wirtschaft/
* _Wie Barcelona eine offene “Smart City” im Dienste des Gemeinwohls plant_. (2018, 9. September). https://netzpolitik.org/2018/freie-software-als-oeffentliches-gut-und-was-rathaeuser-dafuer-tun-koennen/ +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract. Im Interview spricht Francesca Bria, Barcelonas Chief Technology und Digital Innovation Officer, über „Digitale Soziale Innovation“ und passende Strategien um die lokale Wirtschaft, zu entwickeln. Privatsphäre und die demokratische Teilhabe der Bürger*innen auch in einer “Smart City” langfristig zu sichern und zupass:[</div>]
* Macher, J. (n.d.). _Digital und demokratisch (neues deutschland)_. Erhalten am 7. Dezember 2019 von https://www.neues-deutschland.de/artikel/1129769.smart-city-digital-und-demokratisch.html +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract.# In Barcelona bedeutet »Smart City«: Mehr Mitsprache für die Menschen. Andere Städte sind dem Beispiel gefolgt.pass:[</div>]