= Inicializador de iniciativas

Para usar el módulo de iniciativas, querrá revisar las configuraciones que se encuentran en el inicializador. Consulte xref:configure:initializer.adoc[configuración general de inicializador] para más información sobre este archivo.

Necesitarás cambiar en el archivo `config/initializer/decidim.rb`. También puede crear un archivo ad-hoc para estas configuraciones, como `config/initializer/initiatives.rb`.

Después de hacer cambios en este archivo también tendrá que reiniciar el servidor de aplicaciones.

== Creación habilitada

Configuración que define si la creación está permitida para cualquier usuario validado o no. Por defecto es verdadero.

[source,ruby]
....
  config_accessor :creation_enabled do
    true
  end
....

== Umbral de similitud

Establecer que defina el valor mínimo de la similitud para considerar dos iniciativas
similares. Por defecto es 0.25.

[source,ruby]
....
  config_accessor :similarity_threshold do
    0.25
  end
....

== Límite de similaridad

Establecer que define cuántas iniciativas similares se mostrarán.
Por defecto es 5.

[source,ruby]
....
  config_accessor :similarity_limit do
    5
  end
....

== Mínimo de miembros del comité

Minimum number of committee members required to pass the initiative to
technical validation phase. Solo se aplica a las iniciativas creadas por
individuos.

[source,ruby]
....
  config_accessor :minimum_committee_members do
    2
  end
....

== Duración predeterminada del período de firma

Number of days available to collect supports after an initiative has been
published.

[source,ruby]
....
  config_accessor :default_signature_time_period_length do
    120
  end
....

== Componentes por defecto

Componentes habilitados para una nueva iniciativa

[source,ruby]
....
  config_accessor :default_components do
    [:pages, :meetings]
  end
....

== Primer porcentaje de notificación

Notifica cuando se alcanza el porcentaje dado de soportes para una iniciativa
.

[source,ruby]
....
  config_accessor :first_notification_percentage do
    33
  end
....

== Segundo porcentaje de notificación

Notifica cuando se alcanza el porcentaje dado de soportes para una iniciativa
.

[source,ruby]
....
  config_accessor :second_notification_percentage do
    66
  end
....

== Tiempo de caducidad de la caché de estadísticas

Establece el tiempo de caducidad de los datos estadísticos.

[source,ruby]
....
  config_accessor :stats_cache_expiration_time do
    5.minutes
  end
....

== Tiempo máximo para validar el estado

Cantidad máxima de tiempo en la validación de estados.
After this time the initiative will be moved to
discarded state.

[source,ruby]
....
  config_accessor :max_time_in_validating_state do
    60.days
  end
....

== Impresión habilitada

Función de impresión activada. Permite al usuario obtener
una versión impresa de la iniciativa del panel de administración
.

[source,ruby]
....
  config_accessor :print_enabled do
    true
  end
....

== Servicio Timestamp

Establecer un servicio para generar una marca de tiempo en cada voto. El atributo
es el nombre de una clase cuyas instancias son
inicializadas con una cadena que contiene los datos para ser
timestamped y responder a un método timestamp.

[source,ruby]
....
  config_accessor :timestamp_service
....

== Servicio de firmas PDF

Establecer un servicio para agregar una firma a pdf de firmas.
El atributo es el nombre de una clase cuyas instancias son
inicializada con el documento a ser firmado y responder a un método
signed_pdf con la firma añadida.

[source,ruby]
....
  config_accessor :pdf_signature_service
....

== No requiere autorización

Esta bandera permite crear autorizaciones a usuarios no autorizados.

[source,ruby]
....
  config_accessor :do_not_require_authorization do
    false
  end
....