= Publicaciones en inglés

IMPORTANT: Barandiaran, X., Calleja-López, A. & Monterde, A. (2018). Dcidim: redes políticas y tecnopolíticas
para la democracia participativa. __Proyecto de papel blanco de Decidim__. (Puede http://ajbcn-meta-decidim.s3.amazonaws.com/uploads/decidim/attachment/file/2005/White_Paper.pdf[descargar una versión alfa del documento aquí])

== Académico

* Borge, R., Balcells, J. , Padró-Solanet, A. (2019) "A model for the analysis of online citizen deliberation: Barcelona case study", International Journal of Textation. 13, pp. 5671–5695. https://ijoc.org/index.php/ijoc/article/view/10805/2873

== Medios

* Preville, P. (2019, Noviembre 13) _How Barcelona está liderando una nueva era de digital_ https://medium.com/sidewalk-talk/how-barcelona-is-leading-a-new-era-of-digital - 4a033a98cf32
* Graham, T. (2018, 18 de mayo) - _Barcelona encabeza la lucha contra la ciudad inteligente_ https://www.wired.co.uk/article/barcelona-decidim-ada-colau-francesca-bria-decode
* Barandiaran, X. E., & iaran. (24 de abril de 2018). _¿Qué es Decidim?_ https://xabier.barandiaran.net/2018/04/24/what-is-decidim/ +
pase:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstracto. Mucha gente pregunta cuál es este proyecto llamado “Decidim” al que he dedicado mis dos últimos años de trabajo con total dedicación. Quería compartir aquí un breve resumen. Este texto es el…pasaje:[</div>]
* Stark, K. (2017, 9 de mayo). El Decidim de _Barcelona ofrece Plataforma de Código Abierto para Proyectos de Democracia Participatoria_. https://www.shareable.net/blog/barcelonas-decidim-offers-open-source-platform-for-participatory-s3.amazonaws.com/y-projects +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstracto. La palabra Decidim traducida del catalán significa que decidimos, y es el nombre de la infraestructura digital de Barcelona para la democracia participativa. Una parte de base de datos funcional y una parte de declaración política, organizadores afirman que Decidim es clave para una amplia transformación digital que está teniendo lugar en Barcelona: sus instituciones, mercados y economía. as:[</div>]
* _Decidim: Libre democracia participativa de código abierto para ciudades y organizaciones | hacker News_. (n.d.). Recuperado 21 de enero de 2019, de https://news.ycombinator.com/item?id=18952328
* Oikos Denktank. (n.d.). _(W)E-Democracy - ponente 5 (1) - Ciudades E-democráticas - Arnau Monterde y Xabier E. Barandiaran_. Recuperado el 30 de agosto de 2017, desde https://www.youtube.com/watch?v=qrQ8ij4Ekag