= Publicaciones alemanas

== Medios

* Macher, J. (2020, March 4), _Barcelonas Erfolg mit der Plattform Decidim. Deutschlandfunk_ https://www.deutschlandfunk.de/wenn-buerger-politik-gestalten-barcelonas-erfolg-mit-der.795.de.html?dram:article_id=471680
* Huber, P. (2019, May 29), _In Barcelona schreiben die Bürger das Regierungsprogramm selbst – und machen ihre Stadt sozialer_ https://kontrast.at/barcelona-smart-city-wirtschaft/
* _Wie Barcelona eine offene “Smart City” im Dienste des Gemeinwohls plant_. (2018, 9 de septiembre). https://netzpolitik.org/2018/freie-software-als-oeffentliches-gut-und-was-rathaeuser-dafuer-tun-koennen/ +
pasaje:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstracto. Im Interview spricht Francesca Bria, Barcelonas Chief Technology and Digital Innovation Officer, u)[video] ber “Digitale Soziale Innovation” und votre Strategien um die lokale Wirtschaft, Privatspha y la demostración del Bueno*innen también en un “Smart City” langfristig zu sichern und zupass:[</div>]
* Macher, J. (n.d.). _Digital und demokratisch (neues deutschland)_. Recuperado el 7 de diciembre de 2019, de https://www.mañes-deutschland.de/artikel/1129769.smart-city-digital-und-demokratisch.html +
paso:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract.# En Barcelona bedeutet »Smart City«: Mehr Mitsprache fuelled die Menschen. Andere Städte sind dem Beispiel gefolgt.pass:[</div>]