= Contrato social de Decidim

[NOTE]
====
También puede leer el Contrato Social de Decidim en otros idiomas: xref:understand:social-contract-ca.adoc[Català] - xref:understand:social-contract-es.adoc[Castellano]

Si quieres traducirlo a tu propio idioma, por favor https://decidim.org/contact[contáctanos].
====

Código de garantías democráticas y colaboración abierta

Este es el contrato social con el que todos los miembros de la comunidad Decidim están comprometidos a seguir.

Firmando este Contrato Social, cualquier individuo, institución o grupo social de cualquier tipo, se compromete a cumplir los principios establecidos aquí al utilizar, desarrollar y participar en la comunidad de Decidim.

== Software libre y contenido abierto

El código de la plataforma, junto con los módulos, bibliotecas o cualquier otro código que se desarrolle para su funcionamiento e implementación, siempre será Software Libre de Código Abierto con un https://www. nu.org/licenses/agpl-3.0.en.html[Affero GPLv3 license or later versions] cada vez que el código es desarrollado recientemente y con licencias que son compatibles con el anterior cuando el código reutilizado.

Del mismo modo, el contenido, los datos, Las APIs y/o cualquier otra interfaz desplegada para interactuar con cualquier tipo de usuario deben seguir estándares abiertos e interoperables (p. ej. OpenID, RSS, OStatus, etc.), siempre tendiendo a maximizar su integración con los estándares abiertos más utilizados.

Con el fin de maximizar la transparencia y la colaboración ciudadana en los procesos participativos, órganos y mecanismos, el contenido, texto, gráficos, fuentes, audio, vídeo u otros elementos de diseño serán publicados bajo un https://creativecommons. rg/licenses/by-sa/4.0/legATIde[Creative Commons By-SA].

Los datos disponibles a través de la plataforma, especialmente todos los datos que se pueden recopilar de forma sistemática a través de raspadores u otras técnicas de consulta masiva, será publicado y licenciado bajo http://opendatacommons. rg/licencias/odbl[Open Data Commons Open Database License], publicado en formatos estandarizados y accesibles (como CSV, JSON, etc.) y, siempre que sea posible, con herramientas que faciliten el análisis y visualización de datos.

== Transparencia, trazabilidad e integridad

La plataforma, y su configuración actual o futura, desarrollo, despliegue y uso deben asegurar y maximizar, en todo momento, la transparencia, trazabilidad e integridad de documentos, propuestas, debates, decisiones o cualquier otro objeto, mecanismo o proceso participativo.

Por _transparencia_ entendemos que todos los datos relacionados con todos estos mecanismos y procesos participativos están disponibles para su descarga, análisis y tratamiento, siguiendo los más exigentes estándares y formatos para compartir información (accesibilidad, multiformato, etc.).

La transparencia es una condición necesaria para el control de los procesos y mecanismos participativos, pero en cualquier caso nunca debería ser aplicado para el tratamiento de datos personales o contra la defensa de la privacidad de las personas que participan en la plataforma.

Entendemos por _trazabilidad_ la capacidad de rastrear completamente hacia atrás (pasado) y hacia adelante (futuro) lo que sucedió con las propuestas, planes, reglamentos, o cualquier otro objeto de participación o decisión incluido en un proceso o mecanismo. La plataforma debe mostrar en todo momento cómo, por qué, por quién y con qué garantías un determinado tipo de objeto de un proceso participativo fue despedido, aprobado o bloqueado.

Entendemos por _integridad_ la ciudad de un contenido específico, y garantizar que no se haya manipulado o alterado sin que esta modificación sea claramente registrada y visiblemente verificable y auditable. El objetivo de la integridad es evitar la manipulación de propuestas o resultados de procesos o mecanismos participativos.

== Igualdad de oportunidades e indicadores de calidad

Junto con las garantías previamente definidas, la plataforma promete garantizar la igualdad de oportunidades para todas las personas. así como por sus propuestas u otras contribuciones la plataforma podría albergar. La plataforma ofrecerá igualdad de oportunidades de inicio a todos los objetos participativos (propuestas, debates, etc.) para que sean vistos, debatidos, comentados, evaluados o tratados sin discriminación de ningún tipo. En este sentido, la identidad digital de los usuarios de la plataforma siempre será personal y no transferible, la verificación que confiere derechos de decisión a la plataforma también debe ser única, y es la entidad administrativa a cargo de la plataforma quien debe ser responsable de garantizar la no suplantación de una persona o entidad.

La plataforma debe promover, con el objetivo de garantizar su calidad democrática. el uso de indicadores de calidad desarrollados sobre la base de los datos obtenidos a partir de procesos participativos, mecanismos y actividad del usuario. Se promoverá el intercambio de la configuración de los diferentes componentes, así como datos abiertos para la definición de estos indicadores

La igualdad en la participación política de los ciudadanos es uno de los principios fundamentales de cualquier sistema democrático y de la plataforma, no solo tiene que garantizar la igualdad de oportunidades con respecto a los usos y funciones, sino también el derecho de acceso. En este sentido, la entidad encargada de la plataforma asume el compromiso de promover acciones que avancen en la dirección de proporcionar acceso y apoyo a la plataforma para todos los ciudadanos por igual a universalmente Gitar herramientas y recursos apropiados a la plataforma está disponible para cualquier persona que desee utilizar.

== Confianza de datos

La confidencialidad y la privacidad de los datos personales que pueda proporcionar la persona para participar en cualquiera de las funcionalidades y/o posibilidades de participación que proporciona la plataforma estarán garantizadas en todo momento. En ningún caso se transferirán datos personales a terceros. Los datos personales no serán utilizados más allá de lo estrictamente necesario para los fines de registro de usuarios y mejoras en la usabilidad de la plataforma. Siempre que la tecnología de la plataforma lo hace posible, la expresión de preferencias políticas o de voluntad en los procesos de toma de decisiones seguirá siendo inaccesible incluso para el administrador de la plataforma o los servidores que la alberguen.

== Responsabilidad y responsabilidad

Se asumirá el compromiso con los ciudadanos de responder a todas las preguntas y contribuciones en el menor tiempo posible. También se adoptará un compromiso de seguimiento de los resultados de los procesos participativos y de respuesta a aquellas demandas que lo soliciten específicamente. Por último, se asumirá el compromiso de estudiar la incorporación de indicadores para supervisar los procesos de participación una vez finalizados, para evaluar sistemáticamente su implementación.

== Mejora continua y colaboración interinstitucional

Se proporcionarán mecanismos de revisión y evaluación periódicas para facilitar la mejora continua de la plataforma.

Se dará prioridad a la colaboración y el intercambio de experiencias entre las instituciones implicadas en el proyecto. con el objetivo de mejorar, reparar y construir nuevos desarrollos para la mejora continua de la plataforma.

En este sentido, se facilitarán las condiciones y entornos de colaboración al avanzar en mejoras que apunten a un beneficio común de toda la plataforma, posibilitando mecanismos de coordinación entre agencias cuando sea necesario.