= Características generales

:page-partial:

A continuación, describiremos una serie de características generales de la plataforma que no aparecen en los espacios o componentes, o en las características directamente asociadas con los participantes.

== Instalación y ajustes

Decidim **puede instalarse fácilmente **usando el símbolo de comandos en cualquier servidor GNU/Linux con los siguientes servicios instalados: PostgreSQL 9. +, Ruby 2.4.1, NodeJS con yarn (gestión de dependencias JavaScript), ImageMagick y PhantomJS. Un script de instalación automático le permite desplegar todo el sistema de dependencias, bibliotecas, bases de datos y otros servicios automáticamente requeridos en Heroku o Docker [función esperada para 2018Q4].

Los *ajustes* del portal son **personalizables** en los siguientes campos que se rellenan en un formulario del panel de administración: Nombre del portal, perfiles de redes sociales (Twitter, Facebook, Instagram, YouTube, Github); breve descripción; texto de bienvenida; idioma por defecto; imagen de casa; el logo; favicon; prefijo de referencia (identificador único que se aplicará a los elementos del portal) y la URL de la organización.

== Integración con otros servicios y compatibilidad/creación de servicios adicionales

Decidim se puede integrar fácilmente con los siguientes servicios que se pueden instalar o configurar con Decidim:

* *OpenStreetMap*: para mostrar eventos y propuestas con geolocalización
* *Piwik*: análisis de tráfico del sitio web
* *Pad*: consejos de escritura colaborativos en tiempo real (tecnología a determinar)
* *Identidad digital y firma*: integración con el sistema de administración de identidad digital de OAuth2, sistemas basados en blockchain y reconocidos sistemas de gestión de firmas e identidad digital institucional.
* *Sistema distribuido de archivos*: Diseminando o copiando propuestas u otros elementos de la plataforma en un sistema de archivo distribuido (blockchain o tipo IPFS) [Falta característica].
* *Microbloging*: integración/compatibilidad con un protocol/servicio estandarizado y abierto de microblogging como GNU Social o StatusNet tipo para actividades de los participantes (propuestas, observaciones y mensajes) [Falta característica].

Decidim genera automáticamente los siguientes servicios además de los que se pueden navegar en el sitio web o acceder a través de una API:

* *SMTP*: enviando correos electrónicos.
* *Calendario*: integración y compatibilidad con sistemas de gestión de calendarios, creación y actualización automática de calendarios de eventos, etc.

== Multitenencia

La multitenencia de la plataforma se puede utilizar sobre la base de una sola instalación. En otras palabras, una sola instancia de software de Decidim permite desplegar tantos portales (inquilinos) como desee en ajustes específicos para cada uno de los inquilinos. De esta forma, una organización puede crear portales participativos para sus suborganizaciones o diversas organizaciones pueden compartir un servidor y reducir los costes de mantenimiento de sus portales.

== Multiples

Decidim es una plataforma *multiidioma*. Sus idiomas disponibles se configurarán durante su instalación. Los menús, formularios administrativos y, en general, los textos fijos de la plataforma están disponibles en varios idiomas (español, catalán, vasco, italiano, francés, holandés y finés). Un **sistema de traducción colaborativa **en https://crowdin.com/project/decidim permite incorporar nuevos idiomas a la plataforma.

En cuanto al contenido, una vez que los idiomas oficiales de la instancia se han establecido durante la instalación, todo el contenido que se crea desde el panel de administración tiene la opción de ser generado en estos idiomas. El panel de administración permite administrar *contenido en varios idiomas* a través de pestañas. El contenido generado por los usuarios se muestra en la plataforma en un solo idioma (el elegido por el participante a través del selector de idioma en la parte superior de los menús o automáticamente a través de la configuración de idioma de su navegador).

== Estadísticas, datos abiertos y descargas

Además de la interfaz de programación de aplicaciones (API) que automáticamente proporciona acceso a datos públicos, La página principal de Decidim incluye una *tabla general de estadísticas* con los siguientes campos: número de participantes, procesos, propuestas, resultados, reuniones, observaciones y votos.

Otra *tabla de estadísticas para cada proceso participativo* muestra el número de reuniones, propuestas, votos y resultados de un proceso específico.

El panel de administración te permite **exportar las propuestas, resultados y observaciones **de un proceso participativo en formato CSV y JSON y respuestas a encuestas para procesamiento y/o integración con otros sistemas de gestión. Los participantes pueden **descargar los resultados de un proceso participativo y el alcance de su implementación a través de un archivo CSV.

Decidim también tiene un **componente de visualización de datos**a su disposición a nivel general de la plataforma y en un nivel específico (mostrando datos de un Espacio Participatorio específico) [Característica esperada para 2018Q2-3, AjB-Lote2Mod4]. Los siguientes se incluyen entre los gráficos que se muestran:

* **Gráficos interactivos **en forma de línea de tiempo que muestra el desarrollo de los contadores de los diferentes componentes.
* *Mapa de calor* de todas las reuniones, propuestas u otro contenido con etiquetas de geoubicación.
* **Diagramas interactivos**(gráficos de barras o tartas) con los resultados de un proceso (cantidades de cada uno de los proyectos de presupuesto participativo, filtrar por categoría y estado de las propuestas - ya sean seleccionadas o no, etc.)

Todas estas pantallas van acompañadas de una **opción para descargar datos **en formato CSV [Característica esperada para 2018Q2-3, AjB-Lote2Mod4].

== API, diseño adaptable del sitio web y aplicación móvil

Decidim tiene una interfaz o API de programación de aplicaciones que es una serie de llamadas de servicio independientes y datos de la interfaz web de Decidim. Esto permite a terceros desarrollar servicios en la plataforma, liberar automáticamente datos o desarrollar nuevas interfaces, o integrar otros servicios con decidim.

La API viene con *documentación* y una *ontología participativa formal* [No completada]

El *diseño* de la página web de Decidim es completamente *adaptable* (_responsive_), utilizando la filosofía de diseño _mobile-first_ (diseñada primero para móviles y después extendida a sistemas de escritorio y tabletas).

Tanto el diseño del sitio web como la API permiten el desarrollo de aplicaciones móviles para Decidim, y se espera que una *aplicación móvil* se desarrolle pronto.

== Sistemas de clasificación de contenidos

En cuanto a la clasificación de contenidos, en Decidim: campos, categorías y etiquetas (o etiquetas).

*Scopes* son genéricos en toda la plataforma y se dividen en *territoriales* y **tipos de temas**. Las zonas territoriales, una vez definidas, permiten que los elementos de los espacios sean clasificados por territorio (p. ej. si un proceso, un organismo o una iniciativa afecta a un distrito o dos, toda la ciudad, una región o país, dependiendo de la organización). Las áreas temáticas son igualmente definidas para toda la plataforma y permiten la clasificación de los distintos elementos de los espacios participativos.

*Categorías y subcategorías* se utilizan para clasificar el contenido dentro de los distintos espacios y se definen para cada uno de los niveles de los espacios. Así, por ejemplo, un proceso participativo puede incluir varias categorías y subcategorías (el administrador de procesos las define) mientras que las reuniones del proceso, encuestas, propuestas y otros componentes pueden clasificarse bajo estas categorías.

En contraste con los campos y categorías, las *etiquetas* o etiquetas son transversales y libremente definidas por los participantes y pueden aplicarse a cualquier nivel o componente. Las etiquetas pueden ser creadas, embebidas y definidas en el panel de administración. Un sistema de sugerencia de etiquetas permite a las personas que participan elegir etiquetas similares a las que están sugiriendo para etiquetar cualquiera de los elementos de la plataforma. Los elementos pueden ser consultados por etiquetas y las etiquetas más populares mostradas.

== Sistema de ayuda contextual, usabilidad y pruebas de evaluación

Decidim incluye *ayuda contextual editable* para guiar a los participantes individuales y administrativos en el uso de la plataforma. También incluye una **encuesta de evaluación automática** que se realizará sobre los participantes con el fin de identificar errores de usabilidad y procedimientos participativos y mejorar la experiencia de calidad democrática del software .