= Espacios participantes

:page-partial:

Los espacios participantes definen los principales canales participativos. Se muestran en el menú superior principal de la plataforma.

La lógica básica detrás de la estructura de Decidim es que *los componentes trabajan juntos en los espacios participativos*. Hay diferentes tipos de espacios (iniciativas, procesos, consultas y ensambladas) y varias instancias dentro de cada tipo (un proceso para una elección y otro para presupuestos participativos, órgano del consejo para los barrios y otro para los trabajadores, una iniciativa para pedir un cambio en la legislación y otra para que algo se incluya en el orden del día de una reunión plenaria, etc.).

== Procesos

Los procesos participantes requieren un formulario general de *configuración* con los siguientes campos: Título o nombre del proceso; nombre corto para la URL; etiqueta hash (utilizada como referencia para comunicaciones sobre redes sociales); descripción corta; descripción larga; imagen de página de inicio; imagen de banner; fecha de inicio y finalización; campo; grupo promotor (responsable del proceso participativo a nivel político, puede ser la autoridad local o un grupo compuesto por expertos/políticos y asociaciones y otras organizaciones); a quién está dirigido; meta del proceso participativo y estructura participativa. El proceso participativo permite añadir *documentos acompañantes*.

Los procesos participativos se dividen en *etapas* (p. ej. 1. Etapa de información y convocatoria; 2. estadio del diagnóstico; 3. fase de propuestas; 4. Etapa de priorización; 5. fase de decisión; 6. fase de evaluación y 7. estadio de monitorización de resultados). Cada etapa incluye los siguientes campos de configuración: título, descripción, fecha de inicio, fecha de finalización.

*Las luces de anuncios o textos* también pueden ser mostradas en los procesos, tanto en la página de inicio como en el título de cada componente (propuestas, discusiones y debates, etc.) Pueden configurarse mensajes diferentes dependiendo de la etapa particular de un proceso.

Una *herramienta de configuración de procesos participativos* permite la simple activación y desactivación de etapas y sus componentes. La herramienta de configuración de procesos de Decidim es una de sus características más potentes, posibilitando una flexibilidad total en el diseño de procesos participativos en función de las distintas realidades y formas de participación ciudadana.

La característica de **grupos de procesos** permite agrupar varios procesos, como por ejemplo por los presupuestos participativos de diferentes distritos o barrios.

Los procesos participativos pueden tener uno de los siguientes *estados del proceso*: 0) publicados o no publicados; 1) abiertos (iniciados); 2) cerrada (el proceso participativo ha terminado, pero sus resultados aún están en marcha; 3) terminado (tanto el proceso como su fase de resultados están completos) y 4) futuro (aún no ha comenzado).

Un proceso puede ser **resaltado** (que aumenta su visibilidad en la página de inicio).

También existe la posibilidad de **copiar procesos participativos** desde el panel de administración. Esta función permite que los modelos de proceso sean diseñados y copiados para que ciertos detalles puedan ser configurados dentro de los nuevos procesos, evitando la necesidad de crearlos desde cero.

== Colmenas

Decidim permite la **creación y configuración** de *asambleas* participativas o gubernamentales (organismos gubernamentales o participativos; consejos; grupos de trabajo, etc.) definidos como grupos participantes estructurados que, ya sea a nivel individual o representativo, se reúnen periódicamente, con la autoridad para hacer propuestas y decisiones.

La sección *Colmenas* le permite ver una lista completa de todas las Colmenas que se activan y configuran desde el panel de administración. Los *ajustes* básicos requieren que se completen los siguientes campos para cada cuerpo: nombre; imagen; alcance (global, territorial o sectorial); función del organismo (propósito de acción); tipo de organismo (gobierno, ejecutivo, consultivo/asesoramiento, participativo, grupo de trabajo, comisión, etc.). ; fecha de creación; creada por iniciativa de (Ayuntamiento, Ciudadanos u otros); duración (indefinida o fija, en este último caso, fecha de finalización); fecha de inclusión en Decidim; fecha de cierre y razón; cómo se organiza (funciones, competencias, etc.). ; composición; si se puede unir y cómo hacerlo; método de elección de miembros; tipo/función de los miembros dentro del cuerpo; composición de los grupos de trabajo internos como comités de supervisión o consultivos; características del cuerpo; las redes sociales del cuerpo (nombre de red social y vínculo) y los próximos encuentros del cuerpo.

* *Convocatoria de reuniones*: permite enviar invitaciones automáticas de reunión, crear conjuntamente programas y registrar asistencia. Para una lista completa de características vea el componente "meetings".
* *Características de la Colmena*: características abiertas, públicas, transparentes y de otro tipo en cuanto al nivel de participación que permite la asamblea.
* *Composición:* Esto permite definir la composición del cuerpo con mayor detalle, utilizando los perfiles de los participantes asociados con el cuerpo así como otras características. Una visualización de la estructura del cuerpo se genera automáticamente basándose en la composición de los miembros participantes:
** *Tipos de miembros*: Cabello, Vicepresidente, secretarios, otros
** *Origen de membresía*: por sorteo; elección directa; representación de otra asamblea; representación gubernamental, etc.
** *Grupos de trabajo internos*: para la creación de subensamblas. Los grupos de trabajo podrán relacionarse con el cuerpo al que pertenecen
** *Características*: Abrir/cerrado; transparente; con varios permisos de acceso.
* *Display*: nos permite ver los datos internos de cada cuerpo, así como las asociaciones entre ensamblajes
** *Composición*: la estructura de un cuerpo se muestra en forma de un diagrama de círculo
** *Cartas de organización*: nos permiten ver la jerarquía o red de asambleas y sus asociaciones.
* *Mapa y calendario*: nos permite ver la ubicación de todas las Colmenas en un mapa y calendario
* *Participación con otros espacios y componentes*
** *Participación con procesos*: los ensamblajes pueden ser grupos promotores, iniciar un proceso o hacer propuestas dentro de un proceso. La composición de un cuerpo puede ser el resultado de un proceso (para la elección de puestos)
** *Propuestas y resultados*: un organismo puede generar sus propias propuestas o resultados.
*** Muestra cómo se acordó la propuesta (por consenso, mayoría, número de votos, etc.).
** *Reuniones*: Las asambleas tendrán una lista de reuniones asociadas, pero algunas características pueden pasar de una reunión a otra, como las iniciativas ciudadanas para incluir un punto en una agenda. Asimismo, debe ser posible ver los minutos separados de la reunión, ya que están asociados directamente con el cuerpo .

== Iniciativas

*Iniciativas*. Este espacio participativo permite a los ciudadanos hacer propuestas y recoger el *número de firmas y/o aprobaciones solicitadas* dependiendo del tipo (los distintos tipos están establecidos en las normativas municipales), dando lugar al inicio del procedimiento administrativo para su procesamiento y control ciudadano.

Las iniciativas funcionan de la siguiente forma:

* Cualquier persona o asociación ciudadana puede hacer una propuesta de iniciativa ciudadana. Hay *varios tipos de iniciativas* con varios números de aprobaciones/firmas requeridas para su procesamiento (todas son configurables). Desde la página de creación de iniciativas, se puede ver una descripción de cada uno de los métodos, el número de firmas y ejemplos (por ejemplo, vídeos explicativos).
* Para evitar duplicados, una vez creada una iniciativa, el sistema presentará sugerencias de **iniciativas similares** antes de continuar con el siguiente paso. Una vez que se hayan descartado propuestas similares, se mostrará la forma específica para cada tipo de iniciativa. junto con el número mínimo de aprobaciones requeridas. El creador tiene entonces a su disposición una URL que puede ser utilizada para invitar a otros a unirse y apoyar la iniciativa. También se muestra un mapa que muestra las ubicaciones de los puntos de reunión para recoger firmas si las hay.
* Una vez creada la iniciativa, la iniciativa pasará a una etapa de **moderación y validación técnica** donde el personal del Ayuntamiento de la ciudad puede responder de diversas maneras (aprobándola, rechazándola o sugiriendo enmiendas).
* Las iniciativas pueden ser monitoreadas y **notificaciones recibidas en estados actualizados**, además de que su promotor o grupo individual puede enviar periódicamente boletines informativos a otros usos de la plataforma que han optado por seguir la iniciativa.
* Al alcanzar la fecha de finalización especificada, una iniciativa puede tener dos Estados posibles:
** *Rechazado*: donde no alcanza el número mínimo de firmas, se mostrará un mensaje indicando "no cumple con el número de firmas requeridas" y se notificará al creador de la iniciativa.
** *Aceptado*: cuando haya conseguido un número suficiente de firmas o avales será aceptado y comenzará el procedimiento correspondiente.

== Consultas

Consultas (procedimiento de votación en el que todos los participantes de la organización están llamados a votar sobre preguntas específicas) permite a los participantes averiguar acerca de las consultas actuales o prospectivas**, *discutir y debatir* el área temática de la consulta y *supervisar* los resultados. También proporciona una *puerta de entrada a un sistema de votación electrónica* que es externo a Decidim pero integrado en la interfaz con el fin de gestionar y verificar identidades.