= Participantes

:page-partial:

*Los participantes * de Decidim pueden agruparse en tres categorías diferentes:

* *Los visitantes* tienen acceso a todo el contenido de la plataforma sin tener que registrarse ni proporcionar ninguna información.
* Los participantes *registrados* pueden enviar propuestas y comentarios, inscribirse para reuniones, respaldar contenido, seguir a otros participantes y recibir notificaciones, menciones y mensajes privados.
Los usuarios pueden registrarse *directamente* en la plataforma o a través de pasarelas de otras *redes sociales* (Facebook, Twitter o Google+). Para registrarse directamente, los usuarios tendrán que asociar una cuenta de correo electrónico y una contraseña a la cuenta de usuario.
 Los participantes registrados también pueden tener su cuenta oficializada (lo que significa que su nombre de usuario va acompañado de un símbolo especial que indica que realmente son quienes afirman estar en su perfil).
* Los participantes *verificados* pueden tomar decisiones. Decidim ofrece diferentes maneras de llevar a cabo esta verificación.

Los administradores pueden *administrar permisos* para usuarios *registrados* y usuarios *verificados* selectivamente. Por ejemplo, la _creación de propuestas_ puede activarse tanto para usuarios registrados como para usuarios verificados, pero _admite propuestas_ sólo para usuarios verificados.

== Registro público de la actividad administrativa

La verificación manual de los participantes, así como otras acciones administrativas pueden crear vulnerabilidad o pueden permitir que los administradores usen la plataforma de una manera abusiva. Para evitarlo, decidim incluye un *registro público de actividades administrativas* para que estas acciones puedan ser auditadas pública y transparentemente.

== Perfil de usuario y configuración personal

Hay una **página de perfil de usuario **donde los participantes pueden hacer **cambios a sus datos** (tales como cuenta de correo electrónico, contraseña, etc.). , sube y activa una imagen *avatar*, establece notificaciones o elimina su cuenta.

La página de perfil de usuario también permite a los participantes añadir *información adicional* para incluir intereses y habilidades, voluntariamente y seleccionando el nivel de visibilidad de esa información. Esto permite enviar notificaciones personales y los participantes pueden ser emparejados con otros para colaboraciones.

== Monitoreo y notificaciones

Los participantes reciben *notificaciones automatizadas* con respecto al contenido que han creado: respuestas a comentarios y comentarios sobre sus propuestas, así como los resultados de sus propuestas (aceptadas o rechazadas).

Además de las notificaciones automatizadas, los participantes pueden decidir **seguir cualquier elemento** del sistema (otras propuestas, resultados, procesos, ensamblajes, iniciativas, grupos o usuarios, etc.). , y recibir notificaciones.

== Comunicación entre participantes

**Los mensajes instantáneos **pueden ser enviados a los participantes a través de la plataforma, que recibirán una notificación por correo electrónico.

*Menciones* también se puede añadir (en la sección de comentarios) a cualquier usuario registrado y una notificación se enviará automáticamente.

== Grupos de usuarios

Los participantes pueden registrarse en la plataforma como miembros de una o varias organizaciones/coleccionistas. Una vez verificada la organización y la condición de miembro, los participantes pueden llevar a cabo acciones (hacer propuestas o enviar comentarios, etc.). , con su usuario o con el nombre de la organización.

Grupos de usuarios también pueden administrar permisos de usuario y roles de administración asignados a grupos, así como espacios de debate privados o compartir información entre los usuarios del grupo, por ejemplo, que asistieron a una reunión en persona. [Característica que falta actualmente]

== Compromiso

Decidim tiene una serie de características orientadas a _gamifying_ la plataforma, para *atraer y mantener un creciente número de participantes interesados*, así como promover prácticas que impulsen la calidad democrática y la inteligencia colectiva en la participación [se espera el sistema de gamificación para 2018Q2-3, AjB-Lote1].

El sistema de gamificación incluye dos modos, uno centrado en los usuarios y el otro en las propuestas.

* El modo **centrado en el usuario** incorpora un *sistema de puntos* basado en varios criterios (grado de detalle de su perfil de usuario, número de invitaciones a otros en la plataforma, número de propuestas realizadas y comentadas, número de comentarios, número de aprobaciones obtenidas, número de seguidores, etc.)

La combinación de estos y otros indicadores se utiliza para generar rutas de gamificación para cada usuario y definir hilos tales como: la persona más participativa en el distrito, liderazgo en discusiones y debates, etc.

* Gamificación *centrada en propuestas/iniciativas* permite promotores, firmantes y seguidores para impulsar la interacción con ellos incorporando varias *métricas* (número de veces que la propuesta es compartida en redes sociales, grado de controversia (número de comentarios positivos y negativos), calidad de la deliberación (profundidad del árbol de observación), número de incidencias recibidas, etc.