= Características gerais

:page-partial:

Abaixo, vamos esboçar uma série de recursos e características gerais da plataforma que não aparecem nos espaços ou componentes, ou nos recursos diretamente associados aos participantes.

== Instalação e configurações

O Decidim **pode ser facilmente instalado **usando o prompt de comando em qualquer servidor GNU/Linux com os seguintes serviços instalados: PostgreSQL 9. +, Ruby 2.4.1, NodeJS with yarn (JavaScript dependency manage), ImageMagick and PhantomJS. Um script de instalação automático permite que você faça deploy de todo o sistema de dependências, bibliotecas bancos de dados e outros serviços automaticamente requeridos em Heroku ou Docker [recurso esperado para 2018Q4].

As *configurações* do portal são **personalizáveis** nos seguintes campos que são preenchidos em um formulário a partir do painel de administração: Nome do portal, perfis de rede social (Twitter, Facebook, Instagram, YouTube, Github); breve descrição; texto de boas-vindas; linguagem padrão; Imagem do site; logotipo da organização; favicon; prefixo de referência (identificador exclusivo que será aplicado aos elementos do portal) e a URL da organização.

== Integração com outros serviços e compatibilidade/criação de serviços adicionais

O Decidim pode ser facilmente integrado aos seguintes serviços que podem ser instalados ou configurados com o Decidim:

* *OpenStreetMap*: para mostrar eventos e propostas com geo-localização
* *Piwik*: análise de tráfego do site
* *Pad*: quadros de escrita em tempo real colaborativos (tecnologia a ser determinada)
* *Identidade digital e assinatura*: integração com o sistema de gerenciamento de identidade digital OAuth2, sistemas baseados na blockchain e sistemas de gerenciamento de assinaturas e identidades digitais institucionais reconhecidos.
* *Sistema de arquivo distribuído*: Disseminando ou copiando propostas ou outros elementos da plataforma em um sistema de arquivo distribuído (blockchain ou tipo IPFS) [Recurso ausente].
* *Microblogging*: integração/compatibilidade com um protocolo/serviço de microblogs normalizado e aberto, como o tipo GNU Social ou StatusNet para atividades dos participantes (propostas, observações e mensagens) [Recurso ausente].

Decidim gera automaticamente os seguintes serviços além dos que podem ser acessados no site ou acessados através de uma API:

* *SMTP*: enviando emails.
* *Calendário*: integração e compatibilidade com sistemas de gestão de calendários e criação automática e atualização dos calendários de eventos, etc.

== Multiplicação

A multitenância da plataforma pode ser utilizada com base numa única instalação. Por outras palavras, uma única instância de software Decidim permite implantar quantos portais (inquilinos) você deseja em configurações específicas para cada um dos teners. Dessa forma, uma organização pode criar portais participativos para as suas suborganizações ou várias organizações podem compartilhar um servidor e reduzir os custos de manutenção de seus portais.

== Multiidioma

Decidim é uma plataforma *multi-idioma*. Seus idiomas disponíveis serão configurados durante a sua instalação. Menus, formulários administrativos e, em geral, os textos fixos da plataforma estão disponíveis em vários idiomas (espanhol, catalão, basco, italiano, francês, holandês e finlandês). Um **sistema de tradução colaborativa **em https://crowdin.com/project/decidim permite que novos idiomas sejam incorporados na plataforma.

Quanto ao conteúdo, uma vez que as línguas oficiais da instância foram definidas durante a instalação, todo o conteúdo criado a partir do painel de administração tem a opção de ser gerado nestas línguas. O painel de administração permite que *o conteúdo seja gerenciado em vários idiomas* através de guias. O conteúdo gerado pelos usuários é exibido na plataforma em um único idioma (a escolhida pelo participante através do seletor de idioma na parte superior dos menus ou automaticamente através das configurações de idioma do seu navegador).

== Estatísticas, abrir dados e downloads

Além da interface de programação do aplicativo (API) que fornece automaticamente acesso a dados públicos, A página inicial do Decidim apresenta uma *tabela de estatísticas gerais* com os seguintes campos: número de participantes, processos, propostas, resultados, reuniões, observações e votos.

Outra *tabela de estatísticas para cada processo participativo* mostra o número de reuniões, propostas, votos e resultados de um processo específico.

O painel de administração permite que você **exporte as propostas, resultados e observações **de um processo participativo no formato CSV e JSON e respostas a pesquisas de processamento e/ou integração com outros sistemas de gestão. Os participantes podem **baixar os resultados de um processo participativo e a extensão de sua implementação **através de um arquivo CSV.

Decidim também tem um **componente de exibição de dados **à sua disposição no nível geral da plataforma e em um nível específico (mostrando dados de um espaço participativo específico) [Recurso esperado para 2018Q2-3, AjB-Lote2Mod4]. Os seguintes estão incluídos entre os gráficos que são exibidos:

* **Gráficos interativos **na forma de uma linha do tempo mostrando o desenvolvimento dos vários contadores dos componentes.
* *Mapa de calor* de todas as reuniões, propostas ou outro conteúdo com tags de geo-localização.
* **Diagramas interativos **(barra ou gráficos de pizza) com os resultados de um processo (valores de cada um dos projetos orçamentais participativos, filtrar por categoria e status das propostas - selecionado ou não, etc.)

Todas essas telas são acompanhadas por uma **opção de download de dados **no formato CSV [Espera-se um recurso para 2018Q2-3, AjB-Lote2Mod4].

== API, design de site adaptável e aplicativo móvel

O Decidim tem uma interface de programação ou API de aplicativos que é uma série de chamadas de serviço e dados independentes da interface do site do Decidim. Isso permite que terceiros desenvolvam serviços na plataforma, liberem dados automaticamente ou desenvolvam novas interfaces, ou integrem outros serviços com decidim.

A API vem com *documentação* e uma *ontologia participativa* [não concluída]

O *design* do site Decidim é completamente *adaptável* (_responsive_), usando a filosofia de design _mobile-first_ (projetada primeiro para celulares e posteriormente estendida para sistemas de desktop e tablets).

Tanto o design do site como a API permitem o desenvolvimento de aplicativos móveis para Decidim, e um *Aplicativo Móvel* deverá ser desenvolvido em breve.

== Conteúdos sistemas de classificação

Quanto à classificação de conteúdo, os seguintes a serem distinguidos e ajustados em Decidim: campos, categorias e etiquetas (ou tags).

*Escopos* são genéricos em toda a plataforma e divididos em *territorial* e **tipos de tópico. Áreas territoriais, uma vez definidas, permitem que os elementos dos espaços sejam classificados por território (por exemplo, se um processo ou um órgão ou uma iniciativa afecta um distrito ou dois, toda a cidade, uma região ou país, dependendo da organização). As áreas de tópicos estão definidas para toda a plataforma e permitem a classificação dos vários elementos dos espaços participativos.

*Categorias e subcategorias* são usadas para classificar conteúdo dentro dos vários espaços e são definidas para cada um dos níveis dos espaços. Então, por exemplo, um processo participativo pode incluir várias categorias e subcategorias (o administrador do processo define-os), enquanto as reuniões do processo, pesquisas, propostas e outros componentes podem ser classificados nestas categorias.

Em contraste com campos e categorias, *etiquetas* ou tags são cross-cutting e livremente definidas pelos participantes e podem se aplicar a qualquer nível ou componente. Os rótulos podem ser criados, integrados e definidos no painel de administração. Um sistema de sugestão de rótulo permite que as pessoas que participam escolham rótulos semelhantes aos que estão a sugerir para rotular qualquer dos elementos da plataforma. Os elementos podem ser acessados pelos rótulos e os rótulos mais populares exibidos.

== Testes de ajuda contextual, usabilidade e avaliação

Decidim inclui *ajuda contextual editável* para guiar os participantes individuais e administrativos no uso da plataforma. Inclui também um **inquérito de avaliação automático** a ser conduzido sobre os participantes para fins de identificação de erros de usabilidade e de processo participativo e melhoria da experiência de qualidade democrática do software.