= Espaços participativos

:page-partial:

Espaços participativos definem os principais canais participativos. Eles são exibidos no menu superior da plataforma.

A lógica básica por trás da estrutura do Decidim é que *componentes trabalham juntos nos espaços participativos*. Existem diferentes tipos de espaços (iniciativas, processos, consultas e assembleias) e várias instâncias dentro de cada tipo (um processo eleitoral e outro para orçamentos participativos, Órgão conselho de bairros e outro para os trabalhadores, uma iniciativa para exigir uma alteração da legislação e outra para incluir algo numa agenda de reuniões do plenário, etc.).

== processos

Processos participativos requerem um formulário geral de *configuração* com os seguintes campos: Título ou nome do processo; nome curto para URL; hash tag (usado como referência para comunicações nas redes sociais); descrição curta; descrição longa; imagem da página inicial; imagem do banner; data de início e fim; campo; grupo de promotores (responsável pelo processo participativo a nível político, pode ser a autoridade local ou um grupo composto por peritos/políticos e associações da autoridade e outras organizações); quem ela é direcionada; objetivo do processo participativo e da estrutura participativa. O processo participativo permite que *documentos de acompanhamento* sejam adicionados.

Processos participativos são divididos em *estágios* (por exemplo, 1. Informação e reunião de fase; 2. estágio do diagnóstico; 3. Fase das propostas; 4. Estágio de prioridade; 5. estágio de decisão; 6. fase de avaliação e 7. resultados-fase de monitoramento). Cada etapa inclui os seguintes campos de configuração: título, descrição, data de início, data final.

*Destaques dos avisos ou textos* também podem ser exibidos nos processos, tanto na página inicial quanto no título de cada componente (propostas, discussões e debates, etc.) Diferentes mensagens podem ser configuradas dependendo da fase específica de um processo.

Uma *ferramenta de configuração do processo participativo* permite a ativação e desativação simples de estágios e seus componentes. A ferramenta de configuração de processo Decidim é uma das mais poderosas funcionalidades Permitir a total flexibilidade na concepção dos processos participativos de acordo com as diferentes realidades e formas de participação dos cidadãos.

A característica de **grupos de processo** permite agrupar vários processos, como os Orçamentos Participativos de distritos ou bairros diferentes.

Processos participativos podem ter um dos seguintes *status do processo*: 0) publicado ou não publicado; 1) aberto (iniciado); 2) fechado (o processo participativo terminou, mas os resultados ainda estão em curso; 3) terminado (tanto o processo quanto a sua fase de resultados são completados) e 4) futuro (não foi ainda iniciado).

Um processo pode ser **realçado** (que aumenta sua visibilidade na página inicial).

Há também a possibilidade de **copiar processos participativos** do painel de administração. Esta funcionalidade permite que modelos de processo sejam projetados e copiados para que certos detalhes possam ser configurados nos novos processos, evitando a necessidade de as criar a partir do zero.

== Assembleias

O Decidim permite a **criação e configuração** de *assembleias* participativas ou do governo (órgãos do governo ou participativos; conselhos; grupos de trabalho, etc.) definidos como grupos de participantes estruturados que, a nível individual ou representativo, se reúnem periodicamente com autoridade para apresentar propostas e decisões.

A *seção de montagens* permite que você veja uma lista completa de todos os assemblies ativados e configurados a partir do painel de administração. As *configurações* básicas exigem que os seguintes campos sejam completados para cada corpo: nome; imagem; escopo (global, territorial ou sector); função do corpo (finalidade de ação); tipo de órgão (governo, executivo, consultório / consultivo, participativo, grupo de trabalho, comissão, etc. ; data de criação; criada por iniciativa do Conselho Científico, cidadãos ou outros); duração (indefinida ou fixada, neste último caso, data limite); data de inclusão na Decidim; data de encerramento e razão; como é organizada (funções, poderes, etc. ; composição; se ele pode ser unido e como fazer isso; método de escolha dos membros; função/ função dos membros dentro do corpo; composição dos grupos de trabalho internos como comités de acompanhamento ou consultivo; características do corpo; as redes sociais do organismo (nome da rede social e da ligação) e as próximas reuniões do organismo.

* *Reunião de reuniões*: permite enviar convites automáticos de reuniões, criar agendas de forma colaborativa e registrar presença. Para obter uma lista completa de recursos, veja o componente "reuniões".
* *Características da Assembleia*: aberta, pública, transparente e outras características relativas ao nível de participação que o assembly permite.
* *Composição:* Isso permite que a composição do corpo seja definida com mais detalhes, utilizando os perfis dos participantes associados com o corpo e outras características. Uma exibição da estrutura do corpo é gerada automaticamente com base na composição dos membros participantes:
** *Tipos de membros*: presidente, vice-presidente, secretárias, outros
** *Origem da adesão*: por empate; eleições diretas; representação de outra assembleia; representação do governo etc.
** *Grupos de trabalho internos*: para a criação de submontagens. Grupos de trabalho poderão se relacionar ao corpo ao qual pertencem
** *Características*: Aberto/fechado; transparente; com várias licenças de acesso.
* *Exibir*: nos permite ver dados internos sobre cada corpo, bem como associações entre assembleias
** *Composição*: a estrutura de um corpo é mostrada na forma de um diagrama circular
** *Gráficos da organização*: permite-nos visualizar a hierarquia ou rede de assemblies e suas associações.
* *Mapa e calendário*: permita-nos ver a localização de todos os assemblies no mapa e no calendário
* *Envolvimento com outros espaços e componentes*
** *Envolvimento com processos*: conjuntos podem ser grupos promotores, iniciar um processo ou fazer propostas dentro de um processo. A composição de um corpo pode ser o resultado de um processo (para eleger postagens)
** *Propostas e resultados*: um corpo pode gerar suas próprias propostas ou resultados.
*** Mostra como a proposta foi acordada (por consenso, maioria, número de votos, etc.).
** *Reuniões*: assemblies terão uma lista de reuniões associadas, mas algumas características podem saltar de uma reunião para outra, como as iniciativas dos cidadãos, para incluir um ponto numa agenda. Do mesmo modo, deve ser possível ver as actas separadamente da reunião, uma vez que estão directamente associadas ao organismo .

== Iniciativas

*Iniciativas*. Este espaço participativo permite que os cidadãos façam propostas e coletem o *número necessário de assinaturas e/ou endossações* dependendo do tipo (os vários tipos são definidos nas regulamentações municipais), Daqui decorre o início do processo administrativo para o seu tratamento e acompanhamento dos cidadãos.

Iniciativas funcionam da seguinte forma:

* Qualquer pessoa ou associação de cidadãos pode apresentar uma proposta de iniciativa de cidadania. Existem *vários tipos de iniciativas* com vários números de endossos/assinaturas necessários para seu processamento (todas são configuráveis). Na página de criação de iniciativas, uma descrição de cada um dos métodos, o número de assinaturas necessárias e exemplos (por exemplo, vídeos explicativos) podem ser visualizados.
* Para evitar duplicatas, uma vez que foi criada uma iniciativa, o sistema apresentará sugestões para **iniciativas semelhantes** antes de continuar com o seguinte passo. Uma vez excluídas propostas semelhantes, a forma específica será mostrada para cada tipo de iniciativa, juntamente com o número mínimo de endossos exigidos. O criador tem então à sua disposição uma URL que pode ser utilizada para convidar outros a participar e apoiar a iniciativa. Também é exibido um mapa mostrando os locais das reuniões para coletar assinaturas, caso haja alguma.
* Uma vez criada a iniciativa, a iniciativa passará a um estágio de **moderação e validação técnica**. nos casos em que os funcionários da cidade possam responder de várias formas (aprovando-o, rejeitando-o ou sugerindo alterações).
* Iniciativas podem ser monitoradas e **notificações recebidas quando atualizadas** Além disso, o seu promotor ou grupo individual pode enviar periodicamente boletins informativos para outras utilizações da plataforma que optaram por seguir a iniciativa.
* Ao chegar à data de término especificada, uma iniciativa pode ter dois estados possíveis:
** *Rejeitado*: onde ele não alcança o número mínimo de assinaturas, uma mensagem será exibida informando "não atende ao número de assinaturas necessárias" e o criador da iniciativa será notificado.
** *Aceito*: onde alcançou um número suficiente de assinaturas ou endossos, ele será aceito e o procedimento correspondente começará.

== Consultas

As consultas (um processo de votação em que todos os participantes da organização são chamados a votar questões específicas), permite que os participantes **conheçam as consultas atuais ou potenciais**, *discuta e debate* o assunto da consulta e *monitor* os resultados. Ele também fornece um *gateway para um sistema de votação por ele* que é externo para o Decidim, mas integrado na interface para gerenciar e verificar identidades.