= Participantes

:page-partial:

*Participantes* de Decidim podem ser agrupados em três categorias diferentes:

* *Visitantes* têm acesso a todo o conteúdo da plataforma sem precisar se inscrever nem fornecer nenhuma informação.
* Os participantes *registrados* podem enviar propostas e comentários, inscrever-se em reuniões, endossar conteúdo, seguir outros participantes e receber notificações, menções e mensagens privadas.
Os usuários podem se registrar *diretamente* na plataforma ou por meio de gateways de outras *redes sociais* (Facebook, Twitter ou Google+). Para se registrar diretamente, os usuários precisarão associar uma conta de e-mail e uma senha à conta de usuário.
 Os participantes registrados também podem oficializar sua conta (o que significa que seu nome de usuário é acompanhado por um símbolo especial, indicando que são realmente quem eles afirmam estar em seu perfil).
* Os participantes *verificados* podem tomar decisões. O Decidim oferece diferentes formas de realizar esta verificação.

Os administradores podem *gerenciar permissões* para usuários *registrados* e usuários *verificados* de forma seletiva. Por exemplo, _proposal creation_ pode ser ativado para usuários registrados e verificados, mas _suporta apenas propostas_ para usuários verificados.

== Registro público da atividade administrativa

A verificação manual dos participantes, assim como outras ações administrativas podem criar vulnerabilidade ou permitir que os administradores usem a plataforma de uma forma abusiva. Para evitá-lo, o Decidim inclui um *registro público de atividades administrativas* para que essas ações possam ser auditadas pública e transparentemente.

== Configurações de perfil de usuário e pessoal

Há uma **página de perfil do usuário **onde os participantes podem fazer **alterações em seus dados **(como na conta de e-mail, senhas, etc. , enviar e habilitar uma imagem *avatar*, definir notificações ou excluir a conta.

A página de perfil do usuário também permite que os participantes adicionem *informações adicionais* para incluir interesses e habilidades, voluntariamente e escolhendo o nível de visibilidade dessa informação. Isto permite que notificações pessoais sejam enviadas e que os participantes possam ser combinados com outros para colaborações.

== Monitoramento e notificações

Os participantes recebem *notificações automáticas* sobre o conteúdo que criaram: respostas aos comentários e comentários sobre suas propostas, bem como os resultados das suas propostas (aceitadas ou rejeitadas).

Além de notificações automatizadas, os participantes podem decidir **seguir qualquer elemento** do sistema (outras propostas, resultados, processos, montagens, iniciativas, grupos ou usuários, etc. , e receba notificações.

== Comunicação entre participantes

**Mensagens instantâneas **podem ser enviadas aos participantes através da plataforma, que receberão uma notificação por e-mail.

*Menções* também podem ser adicionadas (na seção de comentários) a qualquer usuário registrado, e uma notificação será enviada automaticamente.

== Grupos de usuários

Os participantes podem se registrar na plataforma como membros de uma ou várias organizações/coletivos. Uma vez que a organização e o status da associação forem verificados, os participantes podem realizar ações (fazer propostas ou enviar comentários, etc. , com seu usuário ou com o nome da organização.

Grupos de usuários também podem gerenciar permissões de usuário e funções de administração atribuídas a grupos, Além de espaços de debate privados ou partilha de informação entre os utilizadores de grupos, por exemplo, que participaram numa reunião presencial. [Recurso ausente no momento]

== Envolvimento

Decidim tem uma série de recursos voltados para _gamifying_ a plataforma, para *atrair e manter um número crescente de participantes interessados*, bem como promover práticas que promovam a qualidade democrática e a inteligência colectiva na participação [do sistema de gamificação é esperado para 2018Q2-3, AjB-Lote1].

O sistema de gamificação inclui dois modos, um centrado nos utilizadores e o outro nas propostas.

* O **modo centrado no usuário **incorpora um *sistema de ponto* com base em vários critérios (grau de detalhe de seu perfil de usuário, número de convites para outros na plataforma, número de propostas feitas e comentadas, número de comentários, número de endossos obtidos, número de seguidores, etc.)

A combinação destes e outros indicadores é usada para a geração de rotas de gamificação para cada usuário e definição de threads, tais como: a maioria das pessoas participativas do distrito, liderança em discussões e debates, etc.

* Gamification *centrada em propostas/iniciativas* permite promotores, Assinantes e seguidores para impulsionar a interação com eles incorporando várias *métricas* (número de vezes que a proposta é compartilhada nas redes sociais, grau de controvérsia (número de comentários positivos e negativos), qualidade da deliberação (profundidade da árvore de observação), número de sucessos recebidos, etc.