= Workflows

One neat feature of the Budgets component is the ability to define your own workflows.

This means that you can define multiple Budgets, for instance one for every Neighberhood or District that a City has, and
you can also define multiple rullings regarding how people can vote on those Budgets. By default you have these workflows:

* Vote in one: allows participants to vote in any budget, but only in one.
* Vote in all: allows participants to vote in all budgets.
* Vote in a random component: allows participants to vote only in one budget, selected randomly.

But this can be extended in your application by a developer, by making your own Workflows. For instance for the
https://www.decidim.barcelona/processes/PressupostosParticipatius[2020/2021 Participatory Budgeting Process in Decidim Barcelona],
the people could vote in two districts: the one where they lived and one of their choosing. This was defined in the
https://github.com/AjuntamentdeBarcelona/decidim-barcelona/blob/743be2a210e8745d2dc443166642b285aed2b356/lib/budgets_workflow_pam2021.rb[decidim-barcelona application itself].

You can read more about Worfklows in https://github.com/decidim/decidim/blob/1ab5cd8fdabef48f5be94ff9c30c6bb3bc9a2f8f/decidim-budgets/README.md#budget-workflows[decidim-budgets README.md].

NOTE: You only want to have a voting without much complications? Like a city-wide vote? Don't worry: if you define only one
Budget, then people will go there directly when click in the Budgets section.