= Bienvenido a la documentación de Decidim

Este es el sitio de documentación de Decidim, una plataforma participativa para la democracia creada inicialmente por el Ayuntamiento de Barcelona.

Decidim es un framework que permite a cualquiera crear y configurar una plataforma web, para ser utilizado en forma de una red política para la participación democrática. La plataforma permite a cualquier organización (ayuntamiento, asociación, universidad, ONG, vecindad o cooperativa) crear procesos masivos para la planificación estratégica, presupuesto participativo, diseño colaborativo para reglamentos, espacios urbanos y procesos electorales.

== ¿Nuevo en Decidim?

Usted ha encontrado la documentación para Decidim. Más información sobre el proyecto en https://decidim.org[decidim.org].

[NOTE]
====
Esta es la documentación de la sucursal 'desarrollo'. You can see this same documentation site for other versions: xref:v0.30@ROOT:index.adoc[v0.30], xref:v0.29@ROOT:index.adoc[v0.29], xref:v0.28@ROOT:index.adoc[v0.28] and xref:v0.27@ROOT:index.adoc[v0.27]
====

// * Read the xref:ROOT:getting-started.adoc[Getting Started guide]

La documentación cubre xref:install:index.adoc[installing], xref:configure:index.adoc[configuring], y xref:admin:index.adoc[running] tu propio sitio de Decidim.

Si desea hacer cambios en el código fuente, tenemos documentación para xref:develop:guide.adoc[developers] también.

Si usted es una organización que quiere usar Decidim, o un desarrollador interesado en colaborar en el software, por favor https://decidim.org/contact[póngase en contacto].

Decidim es un esfuerzo de la comunidad, por lo que si encuentras algún error en estas guías, por favor háznoslo saber en hola [at] decidim [dot] org. Todas las ayudas son bienvenidas. Si usted tiene un usuario de GitHub entonces puede incluso proponer cambios a este sitio web con el enlace Editar en cada página.