= Arrière-plan

:experimental:
:icons: font
:page-partial:
:source-highlighter: highlightjs

== Participation citoyenne à la société du réseau

Devenir une société en réseau (ed). Les technologies de l'information et de la communication (désormais, les TIC) et leurs pratiques associées entraînent des changements irréversibles dans le paysage social et politique. De l'association des plus petits résidents à la campagne électorale la plus intensive, d'une organisation de voisinage ou d'un mouvement social à l'Union Européenne, Les relations politiques sont de plus en plus déterminées par l'utilisation de dispositifs et de technologies numériques. Il semble que l'avenir de la participation démocratique et de l'action collective passe par le développement de plates-formes numériques et de processus hybrides, qui rénovent les pratiques traditionnelles et les combinent avec les pratiques numériques (Fuchs, 2007).

Cette transition coïncide avec le déclin des systèmes représentatifs au cours des dernières décennies (Norris, 1999; Pharr & Putnam, 2000; Tormey, 2015), qui a contribué à la remise en question de la légitimité et du sens de la démocratie elle-même, a réduit et souvent identifié à ce système (Crouch, 2004 ; Keane, 2009; Streeck, 2016). Plusieurs auteurs ont utilisé les termes « post-représentation » pour désigner le vide du pouvoir et du sens des institutions représentatives qui vont de la mondialisation à la désaffection et au désinvestissement des citoyens (Brito Vieira et Runciman, 2008; Keane, 2009; Rosanvallon , 2011; Tormey, 2015). Les différentes tentatives visant à stimuler la participation se sont avérées inégales par rapport à la tâche d'inverser ces tendances (Keane, 2011; Tormey, 2015).

Cette crise politique de longue date vient de la crise financière et économique de 2008 et est directement liée à cette crise précédente. Malgré cela, des millions de personnes se sont mobilisées face à la crise, non seulement pour exiger, mais aussi pour expérimenter et construire une véritable démocratie. Le développement clé dans ce domaine a été le mouvement réseau de 15M. C'est dans le contexte de l'hypermédiation technologique que les technologies de l'information et de la communication, utilisés dans les années 1980 et 1990 pour accélérer les flux financiers et la mondialisation (Castells, 1996), devint des espaces et des dispositifs cruciaux pour une réappropriation multitudineuse de la politique, ainsi que pour une expérimentation démocratique (Martinet Ros et al. 2015).

Après quatre années de succès et d'échecs, de nouvelles initiatives citoyennes en mai 2015 ont réussi à prendre le pouvoir dans les principales villes espagnoles, y compris à Barcelone. À cet égard, ils roulaient à la marée de pays tels que l'Islande, où la crise économique a conduit à une période de réappropriation des institutions par les citoyens et à une innovation démocratique fertile basé sur une utilisation intense et créative des TIC.

Depuis 15M, la plupart des expériences visant à introduire de nouvelles formes de démocratie participative et délibérative (Barber, 1984 ; Habermas, 1994, 1996; Della Porta 2013) ont été médiatisés technologiquement. Comme on peut le voir dans le cas de l'Islande (ainsi que d'autres, comme la Finlande), les processus de démocratisation de la mobilisation et de l'autonomisation des citoyens nécessitent une coordination technopolitique (Rodotà 1997; Martinet Ros et coll. 2015) pour atteindre leur richesse et leur capacité maximales. La Technopolitique découle de la politisation des technologies et du remontage technologique de la politique ainsi que du codéveloppement et de la coproduction de la politique et des technologies. En ce qui concerne les formes de participation et de délibération technopolitiques, les pratiques numériques et en face à face, les espaces et les processus se connectent et se retournent les uns des autres, acquérant une dimension multi-couches. Ces dispositifs participatifs sont orientés vers l'augmentation du nombre, variété et parité des acteurs qui « prennent part » au gouvernement commun de la ville, développant et enrichissant les régions, les formes et les périodes dans lesquelles il a lieu et en aidant à renforcer une intelligence collective (Levy, 1997) capable de prendre en charge la complexité de la vie urbaine contemporaine. La technopolitique doit s'attaquer aux nombreuses limites de ce que l'on a appelé la "démocratie numérique" (Hindman, En commençant par se libérer des récits technocentriques et technooptimistes autour de la participation numériquement médiée.

De nouveaux processus participatifs sont en cours d'élaboration dans un contexte plein d'opportunités et de risques. Le programme gouvernemental 2015 et le programme d’action municipale (PAM) pour 2016-2019 élaboré pour la ville de Barcelone donnent la priorité à la participation et, plus spécifiquement, l'innovation et le développement de nouveaux modèles démocratiques de participation. PAM, dont le développement impliquait des milliers de personnes. répond à une demande sociale claire qui appelle à une refonte complète du système démocratique et de ses mécanismes de participation. Cela se produit toutefois dans un contexte défini par: a) les grands secteurs de la population politiquement, économiquement et socialement exclus ; b) la difficulté croissante à accéder à la participation en raison de la situation de crise économique ; c) une crise de la légitimité et de l'opérabilité du système démocratique représentatif et des autorités publiques ; d) une énorme dépendance technologique vis-à-vis des infrastructures et des services privés des entreprises ; e) un contexte juridique et politique défavorable à la démocratie directe, à l'indépendance sociale et à la souveraineté territoriale ; f) un désavantage institutionnel épouvantable dans la compréhension des complexités sociales à travers des techniques d'analyse des données et des modèles de comportement social que possèdent les grandes entreprises technologiques et les services coordonnés numériquement.

[[h.2et92p0]]
== Contrôle des données et infrastructures numériques pour la démocratie

Dans le contexte des nouvelles configurations du capitalisme de l'information (Castells, 1996), ce qu'on appelle le « capitalisme des données » (Lohr, 2015; Morozov, 2015) ou le "capitalisme de surveillance" (Zuboff, 2015), les nouvelles infrastructures numériques de la démocratie risquent de contribuer à des dynamiques contraires à des principes tels que la vie privée et la souveraineté technologique. Exclusif, des plates-formes fermées et opaques destinées à exploiter les activités sociales pour le profit des entreprises fonctionnent comme des espaces non démocratiques occupant de plus en plus de domaines de la vie sociale. Ce modèle est particulièrement dangereux par rapport aux nouvelles infrastructures et processus démocratiques dont nous parlons.

Comparé au modèle d'infrastructure exclusif et organisationnel, le modèle des communes que nous croyons décidim. Le développement d'Arcelona doit être inspiré par des plates-formes de développement où la conception, la propriété et la gestion sont libres, ouvertes et participatives, partagées entre les travailleurs publics et les citoyens (organisés ou non). Sous ce modèle, non seulement le code de la plate-forme, mais aussi les données qui y sont générées sont traitées et appropriées selon la logique de la gestion publique et commune. L'ouverture de tout et de quoi que ce soit à la participation, la marque des virgules en tant que principe politique (par opposition à la sphère privée et même état-public --- Laval & Dardot, 2015), semble être une condition de base pour que les infrastructures participatives soient pleinement fonctionnelles. La participation doit être récursive ici: elle doit aider à définir et à établir les conditions infrastructurelles de sa propre existence et à influer sur la conception, le développement et la gestion des plates-formes participatives numériques ainsi que des processus et des résultats (e. . données) qui sont générées dans celles-ci.

Mettre entre les mains de grandes entreprises de services numériques, l'organisation algorithmique de la vie sociale et le domaine qui nous préoccupe. la participation politique, représente un risque pour la démocratie et la souveraineté technologique que seul un effort public dans les infrastructures numériques peut renverser. Seules les plates-formes basées sur des logiciels de gestion libres, ouverts, transparents, sécurisés et publics offrent des garanties lorsqu'il s'agit de construire des démocraties de meilleure qualité. La démocratie du futur doit donc être bâtie sur des infrastructures démocratiques.