= Bem-vindo à documentação do Decidim

Este é o site de documentação para o Decidim, uma plataforma de democracia participativa criada inicialmente pela Barcelona City Hall.

Decidim é um framework que permite a qualquer pessoa criar e configurar uma plataforma de site, a ser utilizada sob a forma de uma rede política de participação democrática. A plataforma permite que qualquer organização (Câmara Municipal local, associação, universidade, ONG, vizinhança ou cooperativa) crie processos em massa para o planejamento estratégico, orçamentação participativa, design colaborativo para regulamentos, espaços urbanos e processos eleitorais.

== Novo no Decidim?

Você encontrou a documentação do Decidim. Saiba mais sobre o projeto em https://decidim.org[decidim.org].

[NOTE]
====
Esta é a documentação para o ramo 'desenvolvimento'. You can see this same documentation site for other versions: xref:v0.30@ROOT:index.adoc[v0.30], xref:v0.29@ROOT:index.adoc[v0.29], xref:v0.28@ROOT:index.adoc[v0.28] and xref:v0.27@ROOT:index.adoc[v0.27]
====

// * Read the xref:ROOT:getting-started.adoc[Getting Started guide]

A documentação cobre xref:install:index.adoc[installing], xref:configure:index.adoc[configuring], e xref:admin:index.adoc[running] seu próprio site Decidim.

Se você quiser fazer mudanças no código fonte, temos documentação para xref:develop:guide.adoc[developers] também.

Se você é uma organização que quer usar o Decidim ou um desenvolvedor que esteja interessado em colaborar com o software, por favor https://decidim.org/contact[get in touch].

Decidim é um esforço da comunidade, como tal se você encontrar algum erro nesses guias, por favor nos avise na organização [at] decidim [dot]. Qualquer ajuda é bem-vinda. Se você é um usuário do GitHub, então você pode até propor alterações neste site com o link Editar em cada página.