= Publicações em inglês

IMPORTANT: Barandiaran, X., Calleja-López, A. & Monterde, A. (2018). Decidim: redes políticas e tecnopolíticas
para democracia participativa. __Papel branco do Decidim do projeto__. (Você pode http://ajbcn-meta-decidim.s3.amazonaws.com/uploads/decidim/attachment/file/2005/White_Paper.pdf[baixe uma versão alfa do documento aqui])

== Acadêmico

* Borge, R., Balcells, J, Padro├-Solanet, A. (2019) "Um modelo para a análise da deliberação cidadã on-line: estudo de caso de Barcelona", Jornal Internacional da Comunicação. 13, pp. 5671–5695. https://ijoc.org/index.php/ijoc/article/view/10805/2873

== Multimídia

* Diabolo, P. (2019, novembro 13) _Como Barcelona está liderando uma nova era de democracia digital_ https://medium.com/sidewalk-talk/how-barcelona-is-leading-a-new-era-of-digital-democracy-4a033a98cf32
* Graham, T. (2018, Maio 18) - _Barcelona está liderando o combate contra a smart city surveillance_ https://www.wired.co.uk/article/barcelona-decidim-ada-colau-francesca-bria-decode
* Barandiaran, X. E., & iaran. (8 de abril de 2018). _O que é Decidim?_ https://xabier.barandiaran.net/2018/04/24/what-is-decidim/ +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract. Muitas pessoas perguntam o que é este projeto chamado de "Decidim", ao qual eu dediquei meu último dois anos de trabalho com total dedicação. Gostaria de fazer aqui uma breve síntese. Este texto é o texto…pass:[</div>]
* Stark, K. (2017, 9 de maio). _Ofertas Decidim de Barcelona Plataforma de Código Aberto para Projetos de Democracia Participativa_. https://www.shareable.net/blog/barcelonas-decidim-offers-open-source-platform-para-participativos-projetos +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract. A palavra Decidim traduzida do catalão significa que decidimos, e é o nome da infra-estrutura digital de Barcelona para democracia participativa. Uma parte da base de dados funcional e uma parte da declaração política. Os organizadores dizem que o Decidim é fundamental para uma ampla transformação digital que está acontecendo em Barcelona — suas instituições, mercados e economia. ass:[</div>]
* _Decidim: democracia participativa gratuita de código aberto para cidades e organizações. (n.d.). Recuperado 21 de janeiro 2019, de https://news.ycombinator.com/item?id=18952328
* Oikos Denktank. (n.d.). _(W)E-Democracia - palestrante 5 (1) - Cidades E-democráticas - Arnau Monterde e Xabier E. Barandiaran_. Recuperado 30 de agosto de 2017, de https://www.youtube.com/watch?v=qrQ8ij4Ekag