= Publicações em espanhol

== Acadêmico

* Barandiaran, X. E., Calleja, A., Monterde, A., Aragón, P., Linares, J., Romero, C., & Pereira, A. (2017). Decidim: Redes políticas y tecnopolíticas para la democracia participativa. __Recerca__. Visitar o contramestre e fazer anas." Ou seja, 21, 137-150. https://doi.org/10.6035/Recerca.2017.21.8
* Barandiaran, X. E. (2019). Tecnopoliod, tica, municípios radicalizadores e de rematamento. Em L. Roth, A. Monterde, & A. Calleja-Lo├pez (Eds.), _Ciudades Democracia . La revuelta municipalista no ciclo pós-15M_ (p. 173–207). Icaria. http://ciudadesdemocraticas.tecnopolitica.net/
* Borge, R., Balcells, J., Padró-Solanet, A., Batlle, A., Orte, A., & Serra, R.  (2018) La participación política a través de la plataforma Decidim: análisis de 11 municipios catalanes. Paper presentado en el IX Congreso Internacional en Gobierno, Administración y Políticas Públicas GIGAPP. Madrid, 24-27 Septiembre. https://dryfta-assets.s3-accelerate.├assets/congreso2018/abstractfiles/1536574598Laparticipacion_politica_traves_de_la_plataforma_Decidim.pdf
* Sola➲ , J. (2018). _Como são tomadas as decisões em Decidim.barcelona_ [Master Thesis, Pompeu Fabra]. https://repositori.upf.edu/handle/10230/36105
* Barandiaran, X. E., Monterde, A., & Pin, G. (2016a). Decidim.barcelona: autonomia, participació i programari lliure. In Xarxaip (Ed.), _Programari lliure i de codi obert-Societat lliure i govern obert._ (pp. 31–32).
* Barandiaran, X. E., Monterde, A., & Pin, G. (2016b). Decidim.barcelona: autôi^\\a, participacio├n y software libre - Software libre. In Xarxaip (Ed.), _Programari lliure i de codi obert-Societat lliure i govern obert._ (pp. 31–32). http://softwarelibre.xarxaip.cat/18.html
* Aragón, P., Kaltenbrunner, A., Calleja-López, A., Pereira, A., Monterde, A., Barandiaran, X. E., & Gómez, V. (2017). Design de Plataforma Deliberativa: O Estudo de Caso das Discussões On-line em Decidim Barcelona. _Informações Sociais_, 277-287. https://doi.org/10.1007/978-3-319-67256-4_22 +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract. Com a irrupção das TIC e a crise da representação política, Muitas plataformas online foram desenvolvidas com o objectivo de melhorar os processos democráticos participativos. No entanto, no que se refere às plataformas de petição em linha, a investigação anterior não encontrou exemplos de como introduzir efectivamente as discussões, um elemento crucial para promover a deliberação. Neste estudo, centramo-nos no caso de Decidim Barcelona, a plataforma participativa e democrática em linha lançada pelo Município de Barcelona, na qual as propostas podem ser discutidas com uma interface que combina discussões tecidas e alinhamento de comentários com a proposta. Esta abordagem inovadora permite examinar se comentários neutros, positivos ou negativos são mais propensos a gerar cascatas de discussão. Os resultados revelam que, com esta interface, os comentários marcados como alinhados negativamente com a proposta tinham mais probabilidade de envolver usuários em discussões on-line e, Por conseguinte, ajudou a promover a tomada de decisão deliberativa. ass:[</div>]

== Multimídia

* Calleja-López, A., Monterde, A., & Barandiaran, X. E. (7 de outubro de 18). _De las redes sociales a las redes (tecno)políticas: redes de tercera generación para la democracia del siglo XXI_ [Text]. http://tecnopolitica.net/content/de-las-redes-sociales-las-redes-tecnopol%C3%ADticas-redes-de-tercera-generaci%C3%B3n-para-la +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract.# La sociedad deviene (en) vermelh.pass:[</div>]
* _TIPS - Cultura digital - La democracia 2.0_. (7 de fevereiro de 2017). http://www.rtve.es/alacarta/videos/tips/tips-cultura-digital-democracia-20/3896837/ +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract. DICAS - Cultura digital - La democracia 2.0, Dicas on-line, o RTVE.es A Carta. Todos los programas de Tips online en RTVE.es A la Cartapass:[</div>]

[[ref-4881969-FWFFK8LS]]
* Bravo, E. (2016, Julho 20). _Cómo mejorar Barcelona con la participación de sus ciudadanos_ [Magazzine]. http://www.yorokobu.es/barcelona-participacion/ +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract.# El cricket é um deporte muito curioso. Los partidos pueden durar días y, entre sus reglas, está la de parar el juego para tomar el té. Una de las potencias en este deporte es Paquistán, país del que procede parte de la población inmigrante de Barcelona. Muchos de los miembros de esa comunidad llevan años […]pass:[</div>]
* Barandiaran, X. E., Pereira, A., Monterde, A., & Calleja-López, A. (2016). _Plan de desarrollo Decidim Barcelona_. Juntamento do Conselho Municipal de Barcelona. https://decidim-barcelona.s3.amazonaws.com/uploads/decidim/attachment/file/54/Plan_desarrollo_decidim.pdf +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract. Este documento destaca o futuro da plataforma digital de parte parte parte integrante de Barcelona, decidim.barcelona (disponível em URL https://decidim.barcelona). Los principales objetivos de la plataforma son articular, estandarizar, visualizar y comunicar todos los procesos de participación del Ajuntament de Barcelona y de la ciudad ofreciendo un servicio de infraestructura digital para la democracia directa y participativa a todas las escalas territoriales y asociativas de Barcelona. El documento detalla los objetivos de la plataforma, el flujo de desarrollo, las funcionalidades previstas, y un código ético-político.pass:[</div>]
* Participa Pamplona. (7a, 18 de julho). _Decidim Barcelona (Xabier Barandiaran)_. https://www.youtube.com/watch?v=zQYvdwGsg8M +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract.# 1a Jornada de tecnologianocanda,a y democracia (24/05/2017). Infra-estructuras digitais para o democracia. Decidim Barcelona Xabier Barandiaran. Coordinador del proyecto Decidim, asesor de la Regiduría de Participación del Ayuntamiento de Barcelona. Teknologia eta demokraziari buruzko 1. jardunaldia (24/05/2017). Demokrazia partizipatiborako azpiegitura digitalak Decidim Barcelona Xabier Barandiaran. Decidim proiektuaren koordinatzailea eta Bartzelonako Udaleko Partaidetza zinegotziaren aholkulariapass:[</div>]
* Participa Pamplona. (7b, 18 de julho). _Hacia uma democracia participativa inteligente e £tica (Asier Gallastegui y Asier Amezaga)_. https://www.youtube.com/watch?v=z4FTUt8wnRs +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract.# 1a Jornada de Publicidade, a y democracia (24/05/2017). Infra-estructuras digitais para o democracia. Decidim Barcelona Xabier Barandiaran. Coordinador del proyecto Decidim, asesor de la Regiduría de Participación del Ayuntamiento de Barcelona. Teknologia eta demokraziari buruzko 1. jardunaldia (24/05/2017). Demokrazia partizipatiborako azpiegitura digitalak Decidim Barcelona Xabier Barandiaran. Decidim proiektuaren koordinatzailea eta Bartzelonako Udaleko Partaidetza zinegotziaren aholkulariapass:[</div>]
* Participa Pamplona. (2017c, 18). _Metadecidim. Diseño participativo de la plataforma Decidim Barcelona (Andrés Pereira de Lucena)_. https://www.youtube.com/watch?v=I31yY4ip3rk +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract.# 1a Jornada de tecnologianocanamed@@0 a y democracia (24/05/2017). Infra-estructuras digitais para o democracia. Andrés Pereira de Lucena. Presidente de la asociación aLabs, coordinador técnico y arquitecto técnico de Decidim. Teknologia eta demokraziari buruzko 1. jardunaldia (24/05/2017). Demokrazia partizipatiborako azpiegitura digitalak Andrés Pereira de Lucena. aLabs elkarteko lehendakaria eta Dicidimen koordinatzaile teknikoa eta arkitekto teknikoa.pass:[</div>]
* Barandiaran, X. E., & Romero, C. (2018, May 17). _Presentació Decidim Ada Lovelace_. https://www.youtube.com/watch?v=-3eh_v339Cg
* Barcelona Activa. (n.d.). _Fo├rum d’Economies Col·laborativos Procomuns 2017. Activitat paral·lela 3_. Recuperado dia 13 de janeiro de 2018, de https://www.youtube.com/watch?v=IvDsgJcNxnQ
* Digitar Governador. (n.d.). _CGDL2018 - Participació ciutadana: com fer de la política quelcom més proper_. Recuperado 9 de abril de 2018, de https://www.youtube.com/watch?v=7LH6OItIrRU