= My public profile

Every participant has a public profile that shows details about them and their activity on the instance.

To go to this section:

. Sign in as a participant
. Click in the name of the participant in the header
. Click in "My public profile"

The sections available under the public profile are:

* xref:admin:features/my_public_profile/timeline.adoc[Timeline]
* xref:admin:features/my_public_profile/activity.adoc[Activity]
* xref:admin:features/badges.adoc[Badges]
* xref:admin:features/my_public_profile/follows.adoc[Follows]
* xref:admin:features/my_public_profile/followers.adoc[Followers]
* xref:admin:features/my_public_profile/groups.adoc[Groups]

= Badges

The public profile's badges shows which badges the participant has accumulated and what their current level is for each badge.

More information about badges is available on the xref:admin:features/badges.adoc[Badges feature page].

= Followers

The followers section contains a list of participants and groups that are following the participant that the profile belongs to.

= Follows

The follows section contains a list of participants and groups the participant is currently following. By following another participant or a group on the platform, the participant will receive notifications about the activity done by those other participants or groups on the platform. Some participants may also require that they need to be following the other participant before they can exchange private messages with each other.

= Groups

The groups section contains all the groups that the user belongs to. More information about the groups feature is available at the xref:admin:features/my_account/groups.adoc[User groups page].

= Timeline

The timeline view displays the participants activity on the website, including the activity items that should be only visible to the participant currently logged in. This section is not visible to any other user than the participant themselves because it can also contain items that should be visible only to that participant.

= Notifications

In this section participants can see the notifications that the system has sent to them. For instance, if the participant is followign a participatory space or a proposal, they get related notifications about the actions that happen in these sections of the platform.

This section can be accessed through the bell icon in the header bar of the platform. The bell icon shows highlighted as active when there are notifications and dimmer when there are no new notifications for the user right now.


= Notifications

In this section participants can see the notifications that the system has sent to them. For instance, if the participant is followign a participatory space or a proposal, they get related notifications about the actions that happen in these sections of the platform.

This section can be accessed through the bell icon in the header bar of the platform. The bell icon shows highlighted as active when there are notifications and dimmer when there are no new notifications for the user right now.
