name: Vale linting
on:
  pull_request:

jobs:
  prose:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Asciidoctor
        run: sudo apt-get install -y asciidoctor 

      - name: Vale
        uses: errata-ai/vale-action@reviewdog
        with:
          version: 3.7.1
          files: docs/en
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
