= Hintergrund

:experimental:
:icons: font
:page-partial:
:source-highlighter: markiert js

== Bürgerbeteiligung an der Netzwerkgesellschaft

Werde eine Netzwerk(e) Gesellschaft. Informations- und Kommunikationstechnologien (fortan IKT) und ihre damit verbundenen Praktiken bringen unumkehrbare Veränderungen in der sozialen und politischen Landschaft mit sich. Von der kleinsten Bürgervereinigung bis zum intensivsten Wahlkampf, von einer Nachbarschaftsorganisation oder sozialen Bewegung bis hin zur Europäischen Union. Die politischen Beziehungen werden zunehmend durch den Einsatz digitaler Geräte und Technologien bestimmt. Es scheint, dass die Zukunft der demokratischen Teilhabe und des kollektiven Handelns durch die Entwicklung digitaler Plattformen und hybrider Prozesse erfolgen wird. die traditionelle Praktiken erneuern und mit digitalen kombinieren (Fuchs, 2007).

Dieser Übergang fällt mit dem Niedergang der repräsentativen Systeme in den letzten Jahrzehnten (Norris, 1999; Pharr & Putnam, 2000; Tormey, 2015), das zur Infragestellung der Legitimität und des Sinns der Demokratie selbst beigetragen hat, reduzierte und oft mit diesem System identifiziert wurde (Crouch, 2004; Keane, 2009; Streeck, 2016). Mehrere Autoren haben die Begriffe „Post-Repräsentation“ verwendet, um auf die Entleerung von Macht und Bedeutung der repräsentativen Institutionen hinzuweisen, die von der Globalisierung zur Unzufriedenheit und Desinvestition von Bürgern gehen (Brito Vieira und Runciman, 2008; Keane, 2009; Rosanvallon , 2011; Tormey, 2015). Die verschiedenen Versuche, die Beteiligung anzukurbeln, haben sich als ungeeignet erwiesen, diese Trends umzukehren (Keane, 2011; Tormey, 2015).

Diese seit langem andauernde politische Krise kommt auf den Rücken der Finanz- und Wirtschaftskrise von 2008 und steht in direktem Zusammenhang mit dieser früheren Krise. Trotzdem haben Millionen von Menschen angesichts der Krise mobilisiert. Die Absicht nicht nur zu fordern, sondern auch zu experimentieren und eine echte Demokratie aufzubauen. Die Schlüsselentwicklung war hier die 15M Netzwerkbewegung. Vor dem Hintergrund der technologischen Hypermediation sind Informations- und Kommunikationstechnologien verwendet in den 1980er und 1990er Jahren zur Beschleunigung von Finanzströmen und der Globalisierung (Castells, 1996), zu entscheidenden Räumen und Vorrichtungen für eine vielschichtige Wiederaneignung der Politik, sowie demokratische Experimente (Martinet Ros et al. 2015).

Nach vier Jahren zahlreicher Erfolge und Misserfolge gelang es im Mai 2015 neuen politischen Bürgerinitiativen in den wichtigsten spanischen Städten, einschließlich Barcelona, die Macht zu übernehmen. In dieser Hinsicht waren sie auf dem Fluß von Ländern wie Island unterwegs in der die Wirtschaftskrise zu einer Zeit der Wiederaneignung der Bürger der Institutionen und fruchtbaren demokratischen Innovation geführt hatte basierend auf einer intensiven und kreativen Nutzung von IKT.

Seit 15M sollen die meisten Experimente neue Formen der partizipatorischen und deliberativen Demokratie einführen (Barber, 1984; Habermas, 1994, 1996; Della Porta 2013) wurden technologisch vermittelt. Wie aus dem Fall Island (ebenso wie aus anderen Ländern wie Finnland) hervorgeht. die Demokratisierungsprozesse der Mobilisierung und Stärkung der Bürger erfordern technopolitische Koordination (Rodota<unk> 1997; Martinet Ros et al. 2015) um ihren maximalen Reichtum und ihre maximale Kapazität zu erreichen. Technopolitik rührt von der Politisierung von Technologien und technologischen Neuzusammensetzungen der Politik sowie von der Ko-Entwicklung und Ko-Produktion von Politik und Technologie her. Was die Formen der technopolitischen Partizipation und Reflexion betrifft, digitale und persönliche Praktiken, Räume und Prozesse verbinden und leiten sich voneinander ab und erlangen eine mehrschichtige Dimension. Diese teilnehmenden Geräte sind auf die Erhöhung der Anzahl ausgerichtet Vielfalt und Parität von Spielern, die an der gemeinsamen Regierung der Stadt teilnehmen, die die Gebiete erweitern und bereichern Formen und Zeiträume, in denen es stattfindet und zur Förderung einer kollektiven Intelligenz beiträgt (Levy, 1997) in der Lage, die Komplexität des heutigen urbanen Lebens zu übernehmen. Die Technopolitik muss die zahlreichen Grenzen der so genannten „digitalen Demokratie“ (Hindman, 2008) beginnend mit der Befreiung von den technozentrischen und technooptimistischen Erzählungen rund um digital vermittelte Beteiligung.

Neue partizipatorische Prozesse werden in einem Kontext voller Chancen und voller Risiken aufgebaut. Das für die Stadt Barcelona aufgestellte Regierungsprogramm und das städtische Aktionsprogramm (PAM) für 2016-2019 gibt der Beteiligung einen zentralen Platz und Genauer gesagt, Innovation und die Entwicklung neuer demokratischer Beteiligungsmodelle. PAM, deren Entwicklung Tausende von Menschen umfasste einer klaren sozialen Forderung nachkommen, die eine gründliche Neugestaltung des demokratischen Systems und seiner partizipatorischen Mechanismen erfordert. Dies geschieht jedoch in einem Kontext, der von a) großen politischen, wirtschaftlichen und sozial ausgegrenzten Bevölkerungssektoren definiert wurde; b) zunehmende Schwierigkeiten beim Zugang zu Beteiligung infolge der wirtschaftlichen Krise; c) eine Krise der Legitimität und Funktionsfähigkeit des repräsentativen demokratischen Systems und der öffentlichen Behörden; d) eine enorme technologische Abhängigkeit von privaten Unternehmensinfrastrukturen und -dienstleistungen, e) ein juristischer und politischer Kontext, der der direkten Demokratie, der sozialen Unabhängigkeit und der territorialen Souveränität abträglich ist; f) ein gravierender institutioneller Nachteil beim Verständnis sozialer Komplexitäten durch Techniken zur Analyse von Daten des Sozialverhaltens und von Modellen, die große technologische Unternehmen und digital koordinierte Dienstleistungen besitzen.

[[h.2et92p0]]
== Datenkontrolle und digitale Infrastrukturen für die Demokratie

Im Kontext neuer Konfigurationen des Informationskapitalismus (Castells, 1996), so genannter „Datenkapitalismus“ (Lohr, 2015; Morozow, 2015) oder "Überwachungskapitalismus" (Zuboff, 2015), die neuen digitalen Infrastrukturen der Demokratie laufen Gefahr, zu einer Dynamik beizutragen, die gegen die Prinzipien der Privatsphäre und der technologischen Souveränität verstößt. Exklusiv, geschlossene und undurchsichtige Plattformen, die darauf abzielen, soziale Aktivitäten zum Unternehmensgewinn zu nutzen, funktionieren als undemokratische Räume, die immer mehr Bereiche des gesellschaftlichen Lebens besetzen. Dieses Modell ist besonders gefährlich im Hinblick auf die neuen Infrastrukturen und Prozesse der Demokratie, über die wir hier sprechen.

Verglichen mit dem exklusiven und korporativen Infrastrukturmodell, das öffentliche Gemeinsamkeitsmodell, das wir für dezimistisch halten. arcelonas Entwicklung muss inspiriert werden, da sie darauf ausgerichtet ist, Plattformen zu entwickeln, auf denen Design entwickelt wird Eigentum und Management sind frei, offen und partizipativ, geteilt zwischen öffentlichen Arbeitnehmern und Bürgern (organisiert oder nicht). Unter diesem Modell nicht nur der Code der Plattform, sondern auch die darin erzeugten Daten werden gemäß der Logik des öffentlichen und gemeinsamen Managements verarbeitet und angeeignet. Die Öffnung von allem und allem für die Beteiligung, das Kennzeichen der Gemeinsamkeiten als politisches Prinzip (im Gegensatz zur privaten und sogar Staaten-Öffentlichkeit --- Laval & Dardot, 2015) scheint eine Grundvoraussetzung für eine voll funktionsfähige partizipatorische Infrastruktur zu sein. Die Beteiligung muss hier rekursiv sein: Sie muss dabei helfen, die infrastrukturellen Bedingungen ihrer eigenen Existenz zu definieren und zu etablieren und das Design zu beeinflussen. Entwicklung und Management digitaler Beteiligungsplattformen sowie der Prozesse und Ergebnisse (z. . Daten), die in ihnen generiert werden.

Legen Sie großen Unternehmen des digitalen Dienstes, der algorithmischen Organisation des gesellschaftlichen Lebens und dem Bereich, mit dem wir uns beschäftigen. Die politische Partizipation stellt eine Gefahr für die Demokratie und die technologische Souveränität dar, die nur durch öffentliche Gemeinsamkeiten in digitalen Infrastrukturen rückgängig gemacht werden kann. Nur Plattformen, die auf einer freien, offenen, transparenten, sicheren und öffentlichen Verwaltungssoftware basieren, bieten Garantien für den Aufbau von Demokratien von größerer Qualität. Die Demokratie der Zukunft muss also auf demokratischen Infrastrukturen aufgebaut werden.